# Generated by Django 5.2.5 on 2025-11-14 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='discount_campaign',
            field=models.ForeignKey(blank=True, help_text='حملة الخصم المطبقة على هذه الفاتورة', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='sales.discountcampaign', verbose_name='حملة الخصم'),
        ),
    ]
