# Generated by Django 5.2.5 on 2025-09-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('barcode', 'company'), ('code', 'company')},
        ),
        migrations.AlterField(
            model_name='item',
            name='catalog_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم الكتالوج'),
        ),
        migrations.AlterField(
            model_name='itemvariant',
            name='catalog_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=' المتغير رقم الكتالوج'),
        ),
    ]
