# Generated by Django 5.2.5 on 2025-08-30 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_currency_unique_together_alter_currency_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'صنف', 'verbose_name_plural': 'الأصناف'},
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('code', 'company')},
        ),
        migrations.RemoveField(
            model_name='item',
            name='additional_notes',
        ),
        migrations.RemoveField(
            model_name='item',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='item',
            name='attachment_name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='item',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.RemoveField(
            model_name='item',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='item',
            name='custom_fields',
        ),
        migrations.RemoveField(
            model_name='item',
            name='default_warehouse',
        ),
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
        migrations.RemoveField(
            model_name='item',
            name='features',
        ),
        migrations.RemoveField(
            model_name='item',
            name='has_variants',
        ),
        migrations.RemoveField(
            model_name='item',
            name='height',
        ),
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
        migrations.RemoveField(
            model_name='item',
            name='length',
        ),
        migrations.RemoveField(
            model_name='item',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='item',
            name='model_number',
        ),
        migrations.RemoveField(
            model_name='item',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='item',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='item',
            name='purchase_price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sale_price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='item',
            name='specifications',
        ),
        migrations.RemoveField(
            model_name='item',
            name='tax_rate',
        ),
        migrations.RemoveField(
            model_name='item',
            name='unit_of_measure',
        ),
        migrations.RemoveField(
            model_name='item',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='item',
            name='width',
        ),
    ]
