# Generated by Django 5.2.5 on 2025-09-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_item_unique_together_alter_item_catalog_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='رمز الكود'),
        ),
    ]
