# Generated by Django 4.1.13 on 2025-08-23 06:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_data', '0002_businesspartner_itemcomponent_itemconversion_and_more'),
        ('accounting', '0001_initial'),
        ('core', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الصلاحية')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='رمز الصلاحية')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('category', models.CharField(choices=[('sales', 'المبيعات'), ('purchases', 'المشتريات'), ('inventory', 'المخازن'), ('accounting', 'المحاسبة'), ('hr', 'الموارد البشرية'), ('reports', 'التقارير'), ('system', 'النظام')], max_length=50, verbose_name='التصنيف')),
            ],
            options={
                'verbose_name': 'صلاحية مخصصة',
                'verbose_name_plural': 'الصلاحيات المخصصة',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NumberingSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('sales_invoice', 'فاتورة مبيعات'), ('sales_return', 'مرتجع مبيعات'), ('sales_quotation', 'عرض سعر'), ('sales_order', 'أمر بيع'), ('purchase_invoice', 'فاتورة مشتريات'), ('purchase_return', 'مرتجع مشتريات'), ('purchase_order', 'أمر شراء'), ('purchase_request', 'طلب شراء'), ('stock_in', 'سند إدخال'), ('stock_out', 'سند إخراج'), ('stock_transfer', 'سند تحويل'), ('stock_count', 'جرد'), ('journal_entry', 'قيد يومية'), ('payment_voucher', 'سند صرف'), ('receipt_voucher', 'سند قبض'), ('payroll', 'كشف رواتب'), ('loan', 'سلفة/قرض')], max_length=50, verbose_name='نوع المستند')),
                ('prefix', models.CharField(help_text='مثال: INV, PO, JV', max_length=20, verbose_name='البادئة')),
                ('suffix', models.CharField(blank=True, max_length=20, verbose_name='اللاحقة')),
                ('next_number', models.IntegerField(default=1, verbose_name='الرقم التالي')),
                ('padding', models.IntegerField(default=6, help_text='مثال: 6 = 000001', verbose_name='عدد الأصفار')),
                ('yearly_reset', models.BooleanField(default=True, verbose_name='إعادة ترقيم سنوياً')),
                ('include_year', models.BooleanField(default=True, verbose_name='تضمين السنة')),
                ('include_month', models.BooleanField(default=False, verbose_name='تضمين الشهر')),
                ('separator', models.CharField(default='/', help_text='مثال: / أو -', max_length=1, verbose_name='الفاصل')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'تسلسل ترقيم',
                'verbose_name_plural': 'تسلسلات الترقيم',
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('negative_stock_allowed', models.BooleanField(default=False, verbose_name='السماح بالرصيد السالب')),
                ('auto_create_batches', models.BooleanField(default=False, verbose_name='إنشاء دفعات تلقائياً')),
                ('stock_valuation_method', models.CharField(choices=[('fifo', 'الوارد أولاً صادر أولاً'), ('lifo', 'الوارد أخيراً صادر أولاً'), ('average', 'متوسط التكلفة')], default='average', max_length=20, verbose_name='طريقة تقييم المخزون')),
                ('customer_credit_check', models.BooleanField(default=True, verbose_name='فحص حد ائتمان العملاء')),
                ('auto_reserve_stock', models.BooleanField(default=True, verbose_name='حجز المخزون تلقائياً')),
                ('sales_return_period', models.IntegerField(default=7, verbose_name='فترة السماح بالمرتجعات (أيام)')),
                ('auto_create_journal_entries', models.BooleanField(default=True, verbose_name='إنشاء قيود تلقائياً')),
                ('require_approval_journal_entries', models.BooleanField(default=True, verbose_name='تتطلب موافقة على القيود')),
                ('overtime_rate', models.DecimalField(decimal_places=2, default=1.5, help_text='1.5 = مرة ونصف الأجر العادي', max_digits=5, verbose_name='معدل أجر الوقت الإضافي')),
                ('annual_leave_days', models.IntegerField(default=21, verbose_name='أيام الإجازة السنوية')),
                ('session_timeout', models.IntegerField(default=30, verbose_name='مهلة انتهاء الجلسة (دقائق)')),
                ('password_expiry_days', models.IntegerField(default=90, help_text='0 = لا تنتهي', verbose_name='مدة صلاحية كلمة المرور (أيام)')),
                ('force_two_factor', models.BooleanField(default=False, verbose_name='إجبار المصادقة الثنائية')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'إعدادات النظام',
                'verbose_name_plural': 'إعدادات النظام',
            },
        ),
        migrations.RenameField(
            model_name='user',
            old_name='employee_id',
            new_name='emp_number',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.branch', verbose_name='الفرع'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.company', verbose_name='الشركة'),
        ),
        migrations.AddField(
            model_name='branch',
            name='default_cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_branches', to='accounting.costcenter', verbose_name='مركز التكلفة الافتراضي'),
        ),
        migrations.AddField(
            model_name='branch',
            name='default_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_branches', to='base_data.warehouse', verbose_name='المستودع الافتراضي'),
        ),
        migrations.AddField(
            model_name='branch',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AddField(
            model_name='branch',
            name='fax',
            field=models.CharField(blank=True, max_length=20, verbose_name='الفاكس'),
        ),
        migrations.AddField(
            model_name='branch',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='company',
            name='base_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='accounting.currency', verbose_name='العملة الأساسية'),
        ),
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.CharField(default=1, max_length=50, verbose_name='المدينة'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.CharField(default='الأردن', max_length=50, verbose_name='الدولة'),
        ),
        migrations.AddField(
            model_name='company',
            name='default_tax_rate',
            field=models.DecimalField(decimal_places=2, default=16.0, max_digits=5, verbose_name='نسبة الضريبة الافتراضية %'),
        ),
        migrations.AddField(
            model_name='company',
            name='fax',
            field=models.CharField(blank=True, max_length=20, verbose_name='الفاكس'),
        ),
        migrations.AddField(
            model_name='company',
            name='fiscal_year_start_day',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='يوم بداية السنة المالية'),
        ),
        migrations.AddField(
            model_name='company',
            name='fiscal_year_start_month',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='شهر بداية السنة المالية'),
        ),
        migrations.AddField(
            model_name='company',
            name='tax_registration_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='رقم التسجيل الضريبي'),
        ),
        migrations.AddField(
            model_name='company',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, verbose_name='الموقع الإلكتروني'),
        ),
        migrations.AddField(
            model_name='user',
            name='default_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_users', to='base_data.warehouse', verbose_name='المستودع الافتراضي'),
        ),
    ]
