# Generated by Django 5.2.5 on 2025-08-30 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_item_options_alter_item_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['name'], 'verbose_name': 'صنف', 'verbose_name_plural': 'الأصناف'},
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('code', 'company')},
        ),
        migrations.AddField(
            model_name='item',
            name='additional_notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات إضافية'),
        ),
        migrations.AddField(
            model_name='item',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='items/attachments/', verbose_name='ملف مرفق'),
        ),
        migrations.AddField(
            model_name='item',
            name='attachment_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='اسم المرفق'),
        ),
        migrations.AddField(
            model_name='item',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الباركود'),
        ),
        migrations.AddField(
            model_name='item',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='core.brand', verbose_name='العلامة التجارية'),
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='core.itemcategory', verbose_name='التصنيف'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='core.currency', verbose_name='العملة'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict, help_text='حقول إضافية حسب احتياجات العمل', verbose_name='حقول مخصصة'),
        ),
        migrations.AddField(
            model_name='item',
            name='default_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_items', to='core.warehouse', verbose_name='المستودع الافتراضي'),
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, verbose_name='الوصف التفصيلي'),
        ),
        migrations.AddField(
            model_name='item',
            name='features',
            field=models.TextField(blank=True, verbose_name='المميزات'),
        ),
        migrations.AddField(
            model_name='item',
            name='has_variants',
            field=models.BooleanField(default=False, verbose_name='له متغيرات'),
        ),
        migrations.AddField(
            model_name='item',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='الارتفاع (سم)'),
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='items/images/', verbose_name='صورة الصنف'),
        ),
        migrations.AddField(
            model_name='item',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='الطول (سم)'),
        ),
        migrations.AddField(
            model_name='item',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=200, verbose_name='الشركة المصنعة'),
        ),
        migrations.AddField(
            model_name='item',
            name='model_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='رقم الموديل'),
        ),
        migrations.AddField(
            model_name='item',
            name='name_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='الاسم الإنجليزي'),
        ),
        migrations.AddField(
            model_name='item',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AddField(
            model_name='item',
            name='purchase_price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='سعر الشراء'),
        ),
        migrations.AddField(
            model_name='item',
            name='sale_price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='سعر البيع'),
        ),
        migrations.AddField(
            model_name='item',
            name='short_description',
            field=models.TextField(blank=True, max_length=300, verbose_name='وصف مختصر'),
        ),
        migrations.AddField(
            model_name='item',
            name='sku',
            field=models.CharField(blank=True, max_length=100, verbose_name='SKU'),
        ),
        migrations.AddField(
            model_name='item',
            name='specifications',
            field=models.JSONField(blank=True, default=dict, verbose_name='المواصفات الفنية'),
        ),
        migrations.AddField(
            model_name='item',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=16.0, max_digits=5, verbose_name='نسبة الضريبة %'),
        ),
        migrations.AddField(
            model_name='item',
            name='unit_of_measure',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='core.unitofmeasure', verbose_name='وحدة القياس'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='الوزن (كغ)'),
        ),
        migrations.AddField(
            model_name='item',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='العرض (سم)'),
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('barcode', 'company'), ('code', 'company'), ('sku', 'company')},
        ),
    ]
