# Generated by Django 4.1.13 on 2025-08-23 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_data', '0002_businesspartner_itemcomponent_itemconversion_and_more'),
        ('core', '0003_custompermission_numberingsequence_systemsettings_and_more'),
        ('hr', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_account', to='hr.employee', verbose_name='الموظف'),
        ),
        migrations.AddField(
            model_name='user',
            name='signature',
            field=models.ImageField(blank=True, upload_to='signatures/', verbose_name='التوقيع'),
        ),
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.CharField(choices=[('light', 'فاتح'), ('dark', 'داكن'), ('auto', 'تلقائي')], default='light', max_length=20, verbose_name='المظهر'),
        ),
        migrations.AddField(
            model_name='user',
            name='ui_language',
            field=models.CharField(choices=[('ar', 'العربية'), ('en', 'English')], default='ar', max_length=5, verbose_name='لغة الواجهة'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='allowed_warehouses',
            field=models.ManyToManyField(blank=True, help_text='فارغ = كل المستودعات', to='base_data.warehouse', verbose_name='المستودعات المسموحة'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'إنشاء'), ('UPDATE', 'تعديل'), ('DELETE', 'حذف'), ('VIEW', 'عرض'), ('PRINT', 'طباعة'), ('EXPORT', 'تصدير'), ('LOGIN', 'دخول'), ('LOGOUT', 'خروج')], max_length=10, verbose_name='العملية'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='معرف السجل'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='code',
            field=models.CharField(max_length=10, verbose_name='رمز الفرع'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['-timestamp'], name='core_auditl_timesta_189a84_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', '-timestamp'], name='core_auditl_user_id_2a1528_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['model_name', 'object_id'], name='core_auditl_model_n_3fb686_idx'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='core.company', verbose_name='الشركة'),
        ),
        migrations.AddField(
            model_name='numberingsequence',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='فارغ = على مستوى الشركة', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.branch', verbose_name='الفرع'),
        ),
        migrations.AddField(
            model_name='numberingsequence',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='الشركة'),
        ),
        migrations.AddField(
            model_name='custompermission',
            name='groups',
            field=models.ManyToManyField(blank=True, to='auth.group', verbose_name='المجموعات'),
        ),
        migrations.AddField(
            model_name='custompermission',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='custom_permissions', to=settings.AUTH_USER_MODEL, verbose_name='المستخدمون'),
        ),
        migrations.AlterUniqueTogether(
            name='numberingsequence',
            unique_together={('company', 'branch', 'document_type')},
        ),
    ]
