# Generated by Django 5.2.5 on 2025-08-30 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('core', '0004_alter_item_options_alter_item_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='purchase_price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sale_price',
        ),
        migrations.AddField(
            model_name='item',
            name='cost_of_goods_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cogs_items', to='accounting.account', verbose_name='حساب تكلفة البضاعة المباعة'),
        ),
        migrations.AddField(
            model_name='item',
            name='inventory_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='accounting.account', verbose_name='حساب المخزون'),
        ),
        migrations.AddField(
            model_name='item',
            name='purchase_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_items', to='accounting.account', verbose_name='حساب المشتريات'),
        ),
        migrations.AddField(
            model_name='item',
            name='sales_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_items', to='accounting.account', verbose_name='حساب المبيعات'),
        ),
    ]
