# Generated by Django 5.2.5 on 2025-09-26 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_item_image_alter_itemvariant_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesspartner',
            name='sales_representative',
        ),
        migrations.AddField(
            model_name='businesspartner',
            name='commercial_register_file',
            field=models.FileField(blank=True, help_text='ملف السجل التجاري للعميل', null=True, upload_to='partners/commercial_register/', verbose_name='ملف السجل التجاري'),
        ),
        migrations.AddField(
            model_name='businesspartner',
            name='other_attachments',
            field=models.FileField(blank=True, help_text='مرفقات إضافية', null=True, upload_to='partners/other_attachments/', verbose_name='مرفقات أخرى'),
        ),
        migrations.AddField(
            model_name='businesspartner',
            name='payment_letter_file',
            field=models.FileField(blank=True, help_text='كتاب التسديد من البنك', null=True, upload_to='partners/payment_letters/', verbose_name='كتاب التسديد'),
        ),
        migrations.AddField(
            model_name='businesspartner',
            name='tax_exemption_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء الإعفاء'),
        ),
        migrations.AddField(
            model_name='businesspartner',
            name='tax_exemption_file',
            field=models.FileField(blank=True, help_text='كتاب الإعفاء الضريبي من الحكومة', null=True, upload_to='partners/tax_exemptions/', verbose_name='كتاب الإعفاء الضريبي'),
        ),
        migrations.AddField(
            model_name='businesspartner',
            name='tax_exemption_reason',
            field=models.CharField(blank=True, max_length=200, verbose_name='سبب الإعفاء'),
        ),
        migrations.AddField(
            model_name='businesspartner',
            name='tax_exemption_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ بداية الإعفاء'),
        ),
        migrations.AlterField(
            model_name='businesspartner',
            name='tax_status',
            field=models.CharField(choices=[('taxable', 'خاضع'), ('non_taxable', 'غير خاضع'), ('export', 'تصدير')], default='taxable', max_length=20, verbose_name='الحالة الضريبية'),
        ),
        migrations.CreateModel(
            name='PartnerRepresentative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='هاتف المندوب')),
                ('is_primary', models.BooleanField(default=False, verbose_name='المندوب الرئيسي')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='الشركة')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representatives', to='core.businesspartner', verbose_name='العميل')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_assignments', to=settings.AUTH_USER_MODEL, verbose_name='المندوب')),
            ],
            options={
                'verbose_name': 'مندوب العميل',
                'verbose_name_plural': 'مندوبي العملاء',
                'ordering': ['-is_primary', 'user__first_name'],
                'unique_together': {('partner', 'user')},
            },
        ),
    ]
