# Generated by Django 5.2.5 on 2025-09-04 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_item_purchase_price_remove_item_sale_price_and_more'),
    ]

    operations = [
    ]
