# Generated by Django 5.2.5 on 2025-09-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_businesspartner_sales_representative_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partnerrepresentative',
            options={'ordering': ['-is_primary', 'representative_name'], 'verbose_name': 'مندوب العميل', 'verbose_name_plural': 'مندوبي العملاء'},
        ),
        migrations.AlterUniqueTogether(
            name='partnerrepresentative',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='partnerrepresentative',
            name='representative_name',
            field=models.CharField(default=1, help_text='اسم المندوب المسؤول عن هذا العميل', max_length=100, verbose_name='اسم المندوب'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='partnerrepresentative',
            name='user',
        ),
    ]
