# Generated by Django 5.2.5 on 2025-09-05 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_branch_from_basemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='businesspartner',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='item',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='itemcategory',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='itemvariant',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='itemvariantattributevalue',
            name='branch',
        ),
        migrations.AlterUniqueTogether(
            name='numberingsequence',
            unique_together={('company', 'document_type')},
        ),
        migrations.RemoveField(
            model_name='unitofmeasure',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='variantattribute',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='variantvalue',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='numberingsequence',
            name='branch',
        ),
    ]
