# Generated by Django 5.2.5 on 2025-09-06 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0007_remove_brand_branch_remove_businesspartner_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custompermission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='custompermission',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AddField(
            model_name='custompermission',
            name='max_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='الحد الأقصى للمبلغ المسموح (للصلاحيات المالية)', max_digits=12, null=True, verbose_name='الحد الأقصى للمبلغ'),
        ),
        migrations.AddField(
            model_name='custompermission',
            name='permission_type',
            field=models.CharField(choices=[('view', 'عرض'), ('add', 'إضافة'), ('change', 'تعديل'), ('delete', 'حذف'), ('approve', 'موافقة'), ('export', 'تصدير'), ('print', 'طباعة'), ('special', 'صلاحية خاصة')], default='view', max_length=20, verbose_name='نوع الصلاحية'),
        ),
        migrations.AddField(
            model_name='custompermission',
            name='requires_approval',
            field=models.BooleanField(default=False, help_text='هل تحتاج هذه الصلاحية موافقة من مدير أعلى؟', verbose_name='يتطلب موافقة'),
        ),
        migrations.AddField(
            model_name='custompermission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name='PermissionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='اسم المجموعة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, help_text='اتركها فارغة للمجموعات العامة', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='الشركة')),
                ('django_permissions', models.ManyToManyField(blank=True, help_text='صلاحيات Django الأساسية المضمنة في هذه المجموعة', to='auth.permission', verbose_name='صلاحيات Django')),
                ('permissions', models.ManyToManyField(blank=True, help_text='الصلاحيات المخصصة المضمنة في هذه المجموعة', to='core.custompermission', verbose_name='الصلاحيات المخصصة')),
            ],
            options={
                'verbose_name': 'مجموعة صلاحيات',
                'verbose_name_plural': 'مجموعات الصلاحيات',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='permission_groups',
            field=models.ManyToManyField(blank=True, help_text='مجموعات الصلاحيات التي ينتمي إليها المستخدم', to='core.permissiongroup', verbose_name='مجموعات الصلاحيات'),
        ),
    ]
