# Generated by Django 5.2.5 on 2025-09-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0008_custompermission_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissiongroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='permissiongroup',
            name='django_permissions',
            field=models.ManyToManyField(blank=True, help_text='صلاحيات Django الأساسية (CRUD) المضمنة في هذه المجموعة', to='auth.permission', verbose_name='صلاحيات Django'),
        ),
        migrations.AlterField(
            model_name='permissiongroup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
    ]
