# Generated by Django 5.2.5 on 2025-10-17 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_paymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='numberingsequence',
            name='last_reset_year',
            field=models.IntegerField(blank=True, help_text='لتتبع السنة الأخيرة التي تم فيها إعادة الترقيم', null=True, verbose_name='آخر سنة إعادة ترقيم'),
        ),
        migrations.AlterField(
            model_name='numberingsequence',
            name='document_type',
            field=models.CharField(choices=[('sales_invoice', 'فاتورة مبيعات'), ('sales_return', 'مرتجع مبيعات'), ('sales_quotation', 'عرض سعر'), ('sales_order', 'أمر بيع'), ('purchase_invoice', 'فاتورة مشتريات'), ('purchase_return', 'مرتجع مشتريات'), ('purchase_order', 'أمر شراء'), ('purchase_request', 'طلب شراء'), ('stock_in', 'سند إدخال'), ('stock_out', 'سند إخراج'), ('stock_transfer', 'سند تحويل'), ('stock_count', 'جرد'), ('journal_entry', 'قيد يومية'), ('payment_voucher', 'سند صرف'), ('receipt_voucher', 'سند قبض'), ('asset', 'أصل ثابت'), ('asset_transaction', 'عملية على أصل'), ('asset_maintenance', 'صيانة أصل')], max_length=50, verbose_name='نوع المستند'),
        ),
    ]
