# Generated by Django 5.2.5 on 2025-10-23 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_alter_costcenter_cost_center_type'),
        ('core', '0009_numberingsequence_last_reset_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspartner',
            name='customer_account',
            field=models.ForeignKey(blank=True, help_text='حساب المدينين الخاص بهذا العميل', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='accounting.account', verbose_name='حساب العميل'),
        ),
        migrations.AddField(
            model_name='businesspartner',
            name='default_price_list',
            field=models.ForeignKey(blank=True, help_text='قائمة الأسعار المستخدمة لهذا العميل', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='core.pricelist', verbose_name='قائمة الأسعار الافتراضية'),
        ),
        migrations.AddField(
            model_name='businesspartner',
            name='supplier_account',
            field=models.ForeignKey(blank=True, help_text='حساب الدائنين الخاص بهذا المورد', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers', to='accounting.account', verbose_name='حساب المورد'),
        ),
    ]
