# Generated by Django 5.2.5 on 2025-11-14 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_businesspartner_customer_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspartner',
            name='default_salesperson',
            field=models.ForeignKey(blank=True, help_text='مندوب المبيعات المخصص لهذا العميل', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_customers', to='hr.employee', verbose_name='المندوب الافتراضي'),
        ),
        migrations.AddField(
            model_name='businesspartner',
            name='payment_terms',
            field=models.CharField(blank=True, help_text='شروط الدفع للعميل (مثال: نقدي، آجل 30 يوم، إلخ)', max_length=200, verbose_name='شروط الدفع'),
        ),
    ]
