# Generated by Django 5.2.5 on 2025-11-18 16:04

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_businesspartner_default_salesperson_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('job_id', models.CharField(editable=False, help_text='معرف فريد للعملية', max_length=50, unique=True, verbose_name='معرف العملية')),
                ('file_name', models.CharField(max_length=255, verbose_name='اسم الملف')),
                ('file_path', models.FileField(help_text='ملف Excel المستورد', upload_to='imports/%Y/%m/', verbose_name='ملف الاستيراد')),
                ('status', models.CharField(choices=[('PENDING', 'قيد الانتظار'), ('PROCESSING', 'جاري المعالجة'), ('COMPLETED', 'مكتمل'), ('COMPLETED_WITH_ERRORS', 'مكتمل مع أخطاء'), ('FAILED', 'فشل'), ('CANCELLED', 'ملغي')], default='PENDING', max_length=30, verbose_name='الحالة')),
                ('total_rows', models.IntegerField(default=0, verbose_name='إجمالي السطور')),
                ('processed_rows', models.IntegerField(default=0, verbose_name='السطور المعالجة')),
                ('successful_rows', models.IntegerField(default=0, verbose_name='السطور الناجحة')),
                ('failed_rows', models.IntegerField(default=0, verbose_name='السطور الفاشلة')),
                ('errors', models.JSONField(blank=True, default=list, help_text='قائمة بجميع الأخطاء حسب رقم السطر', verbose_name='الأخطاء')),
                ('warnings', models.JSONField(blank=True, default=list, verbose_name='التحذيرات')),
                ('import_type', models.CharField(choices=[('NEW_ITEMS', 'مواد جديدة'), ('UPDATE_PRICES', 'تحديث أسعار'), ('UPDATE_STOCK', 'تحديث مخزون'), ('FULL_UPDATE', 'تحديث كامل')], default='NEW_ITEMS', max_length=50, verbose_name='نوع الاستيراد')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='بدأ في')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='انتهى في')),
                ('duration_seconds', models.IntegerField(blank=True, null=True, verbose_name='المدة (ثوان)')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'عملية استيراد جماعي',
                'verbose_name_plural': 'عمليات الاستيراد الجماعي',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('name', models.CharField(help_text='اسم وصفي للقالب، مثل "قالب مسامير"', max_length=200, verbose_name='اسم القالب')),
                ('code', models.CharField(max_length=50, verbose_name='رمز القالب')),
                ('description', models.TextField(blank=True, help_text='وصف تفصيلي للقالب واستخداماته', verbose_name='الوصف')),
                ('template_data', models.JSONField(default=dict, help_text='البنية الكاملة للمادة بصيغة JSON', verbose_name='بيانات القالب')),
                ('auto_generate_codes', models.BooleanField(default=True, help_text='توليد رموز المواد والمتغيرات تلقائياً', verbose_name='توليد الرموز تلقائياً')),
                ('auto_create_prices', models.BooleanField(default=True, help_text='إنشاء أسعار حسب قواعد التسعير المحددة', verbose_name='إنشاء الأسعار تلقائياً')),
                ('usage_count', models.IntegerField(default=0, help_text='عدد المواد التي تم إنشاؤها من هذا القالب', verbose_name='عدد مرات الاستخدام')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر استخدام')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'قالب مادة',
                'verbose_name_plural': 'قوالب المواد',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='السعر القديم')),
                ('new_price', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='السعر الجديد')),
                ('change_percentage', models.DecimalField(decimal_places=2, help_text='نسبة الزيادة أو النقص في السعر', max_digits=10, verbose_name='نسبة التغيير %')),
                ('change_reason', models.CharField(blank=True, help_text='سبب تغيير السعر', max_length=200, verbose_name='سبب التغيير')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التغيير')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'سجل سعر',
                'verbose_name_plural': 'سجل الأسعار',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('name', models.CharField(max_length=100, verbose_name='اسم القاعدة')),
                ('code', models.CharField(max_length=20, verbose_name='رمز القاعدة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('rule_type', models.CharField(choices=[('MARKUP_PERCENTAGE', 'نسبة الربح'), ('DISCOUNT_PERCENTAGE', 'خصم بالنسبة المئوية'), ('PRICE_FORMULA', 'صيغة تسعير'), ('BULK_DISCOUNT', 'خصم الكميات'), ('SEASONAL_PRICING', 'تسعير موسمي')], default='MARKUP_PERCENTAGE', max_length=30, verbose_name='نوع القاعدة')),
                ('percentage_value', models.DecimalField(blank=True, decimal_places=2, help_text='مثال: 15.00 تعني 15%', max_digits=5, null=True, verbose_name='قيمة النسبة %')),
                ('formula', models.JSONField(blank=True, default=dict, help_text='صيغة التسعير بصيغة JSON، مثل: {"base": "cost", "multiplier": 1.5, "add": 10}', verbose_name='الصيغة')),
                ('min_quantity', models.DecimalField(blank=True, decimal_places=3, help_text='القاعدة تطبق من هذه الكمية فما فوق', max_digits=10, null=True, verbose_name='الكمية الأدنى')),
                ('max_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='الكمية الأقصى')),
                ('apply_to_all_items', models.BooleanField(default=False, verbose_name='تطبيق على جميع المواد')),
                ('priority', models.IntegerField(default=10, help_text='القواعد ذات الأولوية الأعلى تطبق أولاً', verbose_name='الأولوية')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ النهاية')),
            ],
            options={
                'verbose_name': 'قاعدة تسعير',
                'verbose_name_plural': 'قواعد التسعير',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UoMConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('conversion_factor', models.DecimalField(decimal_places=6, help_text='عدد الوحدات الأساسية في وحدة واحدة. مثال: دزينة = 12', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))], verbose_name='معامل التحويل')),
                ('formula_expression', models.CharField(blank=True, help_text='صيغة نصية توضيحية، مثل: "1 دزينة = 12 قطعة"', max_length=200, verbose_name='صيغة التحويل')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'تحويل وحدة قياس',
                'verbose_name_plural': 'تحويلات وحدات القياس',
                'ordering': ['item', 'variant', 'from_uom'],
            },
        ),
        migrations.CreateModel(
            name='VariantLifecycleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('CREATED', 'إنشاء'), ('UPDATED', 'تحديث'), ('DISCONTINUED', 'إيقاف الإنتاج'), ('REACTIVATED', 'إعادة تفعيل'), ('PRICE_CHANGED', 'تغيير سعر'), ('COST_CHANGED', 'تغيير تكلفة'), ('BARCODE_CHANGED', 'تغيير باركود'), ('UOM_ADDED', 'إضافة وحدة قياس'), ('UOM_REMOVED', 'حذف وحدة قياس'), ('ATTRIBUTE_CHANGED', 'تغيير خاصية'), ('IMAGE_UPDATED', 'تحديث صورة'), ('STOCK_ADJUSTED', 'تعديل مخزون')], max_length=30, verbose_name='نوع الحدث')),
                ('event_description', models.TextField(help_text='وصف تفصيلي للحدث', verbose_name='وصف الحدث')),
                ('old_values', models.JSONField(blank=True, default=dict, help_text='القيم قبل التغيير', verbose_name='القيم القديمة')),
                ('new_values', models.JSONField(blank=True, default=dict, help_text='القيم بعد التغيير', verbose_name='القيم الجديدة')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='التوقيت')),
                ('reason', models.CharField(blank=True, help_text='سبب التغيير', max_length=200, verbose_name='السبب')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user_agent', models.CharField(blank=True, max_length=300, verbose_name='معلومات المتصفح')),
            ],
            options={
                'verbose_name': 'حدث دورة حياة متغير',
                'verbose_name_plural': 'أحداث دورة حياة المتغيرات',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterModelOptions(
            name='pricelistitem',
            options={'ordering': ['item__name', 'variant__code', 'uom__name'], 'verbose_name': 'سعر مادة', 'verbose_name_plural': 'أسعار المواد'},
        ),
        migrations.AlterModelOptions(
            name='unitofmeasure',
            options={'ordering': ['uom_type', 'name'], 'verbose_name': 'وحدة قياس', 'verbose_name_plural': 'وحدات القياس'},
        ),
        migrations.AlterUniqueTogether(
            name='pricelistitem',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='item',
            name='unit_of_measure',
        ),
        migrations.AddField(
            model_name='item',
            name='base_uom',
            field=models.ForeignKey(blank=True, help_text='الوحدة الأساسية للمادة (مثل: قطعة)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='core.unitofmeasure', verbose_name='الوحدة الأساسية'),
        ),
        migrations.AddField(
            model_name='item',
            name='discontinued_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ التوقف'),
        ),
        migrations.AddField(
            model_name='item',
            name='discontinued_reason',
            field=models.CharField(blank=True, max_length=200, verbose_name='سبب التوقف'),
        ),
        migrations.AddField(
            model_name='item',
            name='is_discontinued',
            field=models.BooleanField(default=False, help_text='المادة متوقفة عن الإنتاج لكن يمكن الرجوع إليها', verbose_name='متوقف الإنتاج'),
        ),
        migrations.AddField(
            model_name='itemvariant',
            name='base_price',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='السعر الأساسي قبل تطبيق قوائم الأسعار', max_digits=15, null=True, verbose_name='السعر الأساسي'),
        ),
        migrations.AddField(
            model_name='itemvariant',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='سعر التكلفة - يستخدم في حساب الأسعار', max_digits=15, null=True, verbose_name='سعر التكلفة'),
        ),
        migrations.AddField(
            model_name='itemvariant',
            name='discontinued_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ التوقف'),
        ),
        migrations.AddField(
            model_name='itemvariant',
            name='is_discontinued',
            field=models.BooleanField(default=False, verbose_name='متوقف الإنتاج'),
        ),
        migrations.AddField(
            model_name='pricelistitem',
            name='uom',
            field=models.ForeignKey(blank=True, help_text='السعر لهذه الوحدة. فارغ = الوحدة الأساسية', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='price_list_items', to='core.unitofmeasure', verbose_name='وحدة القياس'),
        ),
        migrations.AddField(
            model_name='unitofmeasure',
            name='is_base_unit',
            field=models.BooleanField(default=False, help_text='هل هذه الوحدة هي الأساس في تصنيفها؟ (مثل: قطعة، كيلو، متر)', verbose_name='وحدة أساسية'),
        ),
        migrations.AddField(
            model_name='unitofmeasure',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AddField(
            model_name='unitofmeasure',
            name='rounding_precision',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.01'), help_text='مثال: 0.01 للتقريب لأقرب 0.01، 1 للتقريب لأقرب عدد صحيح', max_digits=10, verbose_name='دقة التقريب'),
        ),
        migrations.AddField(
            model_name='unitofmeasure',
            name='symbol',
            field=models.CharField(blank=True, help_text='مثل: كجم، م، ل', max_length=10, verbose_name='الرمز المختصر'),
        ),
        migrations.AddField(
            model_name='unitofmeasure',
            name='uom_type',
            field=models.CharField(choices=[('UNIT', 'وحدة'), ('WEIGHT', 'وزن'), ('LENGTH', 'طول'), ('VOLUME', 'حجم'), ('AREA', 'مساحة'), ('TIME', 'وقت')], default='UNIT', help_text='نوع وحدة القياس', max_length=10, verbose_name='نوع الوحدة'),
        ),
        migrations.AlterField(
            model_name='itemvariant',
            name='catalog_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم الكتالوج'),
        ),
        migrations.AlterField(
            model_name='pricelistitem',
            name='min_quantity',
            field=models.DecimalField(decimal_places=3, default=1, help_text='السعر يطبق من هذه الكمية فما فوق', max_digits=10, verbose_name='الكمية الأدنى'),
        ),
        migrations.AlterUniqueTogether(
            name='pricelistitem',
            unique_together={('price_list', 'item', 'variant', 'uom', 'min_quantity')},
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', '-timestamp'], name='core_auditl_user_id_2a1528_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['model_name', 'object_id'], name='core_auditl_model_n_3fb686_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['-timestamp'], name='core_auditl_timesta_189a84_idx'),
        ),
        migrations.AddIndex(
            model_name='pricelistitem',
            index=models.Index(fields=['item', 'variant', 'uom'], name='core_pricel_item_id_164e38_idx'),
        ),
        migrations.AddField(
            model_name='bulkimportjob',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='الشركة'),
        ),
        migrations.AddField(
            model_name='bulkimportjob',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة'),
        ),
        migrations.AddField(
            model_name='itemtemplate',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='core.itemcategory', verbose_name='التصنيف'),
        ),
        migrations.AddField(
            model_name='itemtemplate',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='الشركة'),
        ),
        migrations.AddField(
            model_name='itemtemplate',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة'),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تم التغيير بواسطة'),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='price_list_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='core.pricelistitem', verbose_name='سعر المادة'),
        ),
        migrations.AddField(
            model_name='pricingrule',
            name='apply_to_categories',
            field=models.ManyToManyField(blank=True, related_name='pricing_rules', to='core.itemcategory', verbose_name='التصنيفات المشمولة'),
        ),
        migrations.AddField(
            model_name='pricingrule',
            name='apply_to_items',
            field=models.ManyToManyField(blank=True, related_name='pricing_rules', to='core.item', verbose_name='المواد المشمولة'),
        ),
        migrations.AddField(
            model_name='pricingrule',
            name='apply_to_price_lists',
            field=models.ManyToManyField(blank=True, related_name='pricing_rules', to='core.pricelist', verbose_name='قوائم الأسعار المشمولة'),
        ),
        migrations.AddField(
            model_name='pricingrule',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='الشركة'),
        ),
        migrations.AddField(
            model_name='pricingrule',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة'),
        ),
        migrations.AddField(
            model_name='uomconversion',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='الشركة'),
        ),
        migrations.AddField(
            model_name='uomconversion',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة'),
        ),
        migrations.AddField(
            model_name='uomconversion',
            name='from_uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversions_from', to='core.unitofmeasure', verbose_name='من وحدة'),
        ),
        migrations.AddField(
            model_name='uomconversion',
            name='item',
            field=models.ForeignKey(blank=True, help_text='اتركها فارغة للتحويلات العامة', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uom_conversions', to='core.item', verbose_name='المادة'),
        ),
        migrations.AddField(
            model_name='uomconversion',
            name='variant',
            field=models.ForeignKey(blank=True, help_text='تحويل خاص بمتغير معين', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uom_conversions', to='core.itemvariant', verbose_name='المتغير'),
        ),
        migrations.AddField(
            model_name='variantlifecycleevent',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تم بواسطة'),
        ),
        migrations.AddField(
            model_name='variantlifecycleevent',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle_events', to='core.itemvariant', verbose_name='المتغير'),
        ),
        migrations.AddIndex(
            model_name='bulkimportjob',
            index=models.Index(fields=['status', '-created_at'], name='core_bulkim_status_8b09cb_idx'),
        ),
        migrations.AddIndex(
            model_name='bulkimportjob',
            index=models.Index(fields=['company', '-created_at'], name='core_bulkim_company_475091_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='itemtemplate',
            unique_together={('company', 'code')},
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['price_list_item', '-changed_at'], name='core_priceh_price_l_e32ae0_idx'),
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['-changed_at'], name='core_priceh_changed_ef1283_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pricingrule',
            unique_together={('company', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='uomconversion',
            unique_together={('item', 'variant', 'from_uom', 'company')},
        ),
        migrations.AddIndex(
            model_name='variantlifecycleevent',
            index=models.Index(fields=['variant', '-timestamp'], name='core_varian_variant_544b69_idx'),
        ),
        migrations.AddIndex(
            model_name='variantlifecycleevent',
            index=models.Index(fields=['event_type', '-timestamp'], name='core_varian_event_t_dbcb7e_idx'),
        ),
        migrations.AddIndex(
            model_name='variantlifecycleevent',
            index=models.Index(fields=['-timestamp'], name='core_varian_timesta_9252d0_idx'),
        ),
    ]
