# Generated by Django 5.2.5 on 2025-11-18 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_bulkimportjob_itemtemplate_pricehistory_pricingrule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitofmeasure',
            name='uom_type',
            field=models.CharField(choices=[('UNIT', 'وحدة'), ('WEIGHT', 'وزن'), ('LENGTH', 'طول'), ('VOLUME', 'حجم'), ('AREA', 'مساحة'), ('TIME', 'وقت')], default='UNIT', help_text='نوع وحدة القياس (قديم - استخدم المجموعة بدلاً منه)', max_length=10, verbose_name='نوع الوحدة'),
        ),
        migrations.CreateModel(
            name='UoMGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('name', models.CharField(help_text='مثال: الوزن، الطول، الحجم', max_length=100, verbose_name='اسم المجموعة')),
                ('code', models.CharField(help_text='رمز فريد بالإنجليزية، مثال: WEIGHT, LENGTH', max_length=20, verbose_name='رمز المجموعة')),
                ('description', models.TextField(blank=True, help_text='وصف تفصيلي للمجموعة واستخداماتها', verbose_name='الوصف')),
                ('allow_decimal', models.BooleanField(default=True, help_text='هل يمكن استخدام كميات عشرية؟ (مثل: 2.5 كجم)', verbose_name='السماح بالأرقام العشرية')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('base_uom', models.ForeignKey(blank=True, help_text='الوحدة الأساسية التي تُحسب التحويلات على أساسها (مثل: كيلوجرام للوزن)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups_as_base', to='core.unitofmeasure', verbose_name='الوحدة الأساسية')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='الشركة')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة')),
            ],
            options={
                'verbose_name': 'مجموعة وحدات قياس',
                'verbose_name_plural': 'مجموعات وحدات القياس',
                'db_table': 'core_uomgroup',
                'ordering': ['name'],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.AddField(
            model_name='unitofmeasure',
            name='uom_group',
            field=models.ForeignKey(blank=True, help_text='المجموعة التي تنتمي إليها هذه الوحدة', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='units', to='core.uomgroup', verbose_name='مجموعة الوحدات'),
        ),
    ]
