# Generated by Django 5.2.5 on 2025-11-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_alter_costcenter_cost_center_type'),
        ('core', '0013_week2_uom_groups'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['company', 'is_active'], name='core_item_company_337b65_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['company', 'code'], name='core_item_company_dec2cc_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['category', 'is_active'], name='core_item_categor_947fe2_idx'),
        ),
        migrations.AddIndex(
            model_name='itemvariant',
            index=models.Index(fields=['item', 'is_active'], name='core_itemva_item_id_959964_idx'),
        ),
        migrations.AddIndex(
            model_name='itemvariant',
            index=models.Index(fields=['item', 'code'], name='core_itemva_item_id_174c8c_idx'),
        ),
        migrations.AddIndex(
            model_name='itemvariant',
            index=models.Index(fields=['code'], name='core_itemva_code_08f84b_idx'),
        ),
    ]
