# Generated by Django 5.2.5 on 2025-11-21 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_item_core_item_company_337b65_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='الفرع التابع له المستودع', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='core.branch', verbose_name='الفرع'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='warehouse_type',
            field=models.CharField(choices=[('main', 'رئيسي'), ('branch', 'فرعي'), ('transit', 'ترانزيت'), ('damaged', 'تالف'), ('returns', 'مرتجعات'), ('quarantine', 'حجر صحي'), ('virtual', 'افتراضي')], default='branch', help_text='تصنيف المستودع حسب الاستخدام', max_length=20, verbose_name='نوع المستودع'),
        ),
    ]
