# Generated by Django 5.2.5 on 2025-11-21 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_warehouse_branch_warehouse_warehouse_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemvariant',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='إذا لم يُحدد، يُستخدم ارتفاع المادة الأساسية', max_digits=10, null=True, verbose_name='الارتفاع الخاص (سم)'),
        ),
        migrations.AddField(
            model_name='itemvariant',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='إذا لم يُحدد، يُستخدم طول المادة الأساسية', max_digits=10, null=True, verbose_name='الطول الخاص (سم)'),
        ),
        migrations.AddField(
            model_name='itemvariant',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='إذا لم يُحدد، يُستخدم عرض المادة الأساسية', max_digits=10, null=True, verbose_name='العرض الخاص (سم)'),
        ),
        migrations.AlterField(
            model_name='itemvariant',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='إذا لم يُحدد، يُستخدم وزن المادة الأساسية', max_digits=10, null=True, verbose_name='الوزن الخاص'),
        ),
    ]
