# Generated by Django 5.2.5 on 2025-11-21 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_add_dimensions_to_itemvariant'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerItemPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('last_purchase_price', models.DecimalField(blank=True, decimal_places=3, help_text='آخر سعر شراء من هذا المورد', max_digits=12, null=True, verbose_name='آخر سعر شراء')),
                ('last_purchase_date', models.DateField(blank=True, null=True, verbose_name='تاريخ آخر شراء')),
                ('last_purchase_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='كمية آخر شراء')),
                ('last_sale_price', models.DecimalField(blank=True, decimal_places=3, help_text='آخر سعر بيع لهذا العميل', max_digits=12, null=True, verbose_name='آخر سعر بيع')),
                ('last_sale_date', models.DateField(blank=True, null=True, verbose_name='تاريخ آخر بيع')),
                ('last_sale_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='كمية آخر بيع')),
                ('total_purchased_quantity', models.DecimalField(decimal_places=3, default=0, help_text='إجمالي ما تم شراؤه من هذا المورد', max_digits=15, verbose_name='إجمالي الكمية المشتراة')),
                ('total_sold_quantity', models.DecimalField(decimal_places=3, default=0, help_text='إجمالي ما تم بيعه لهذا العميل', max_digits=15, verbose_name='إجمالي الكمية المباعة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='الشركة')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_prices', to='core.item', verbose_name='المادة')),
                ('item_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_prices', to='core.itemvariant', verbose_name='المتغير')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_prices', to='core.businesspartner', verbose_name='الشريك التجاري')),
            ],
            options={
                'verbose_name': 'سعر المادة للشريك',
                'verbose_name_plural': 'أسعار المواد للشركاء',
                'ordering': ['-last_purchase_date', '-last_sale_date'],
                'indexes': [models.Index(fields=['partner', 'item'], name='core_partne_partner_206689_idx'), models.Index(fields=['partner', 'item_variant'], name='core_partne_partner_cbbe29_idx'), models.Index(fields=['last_purchase_date'], name='core_partne_last_pu_134528_idx'), models.Index(fields=['last_sale_date'], name='core_partne_last_sa_884272_idx')],
                'unique_together': {('company', 'partner', 'item', 'item_variant')},
            },
        ),
    ]
