# Generated by Django 5.2.5 on 2025-12-07 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_partner_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspartner',
            name='current_balance',
            field=models.DecimalField(decimal_places=3, default=0, help_text='الرصيد المستحق على العميل (يتم تحديثه تلقائياً)', max_digits=15, verbose_name='الرصيد الحالي'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='credit_restore_on_check_date',
            field=models.BooleanField(default=False, help_text='إذا كان نعم، يتم استرجاع ائتمان العميل عند تاريخ صرف الشيك وليس عند إدخال سند القبض', verbose_name='استرجاع الائتمان عند تاريخ صرف الشيك'),
        ),
    ]
