# Generated by Django 5.2.5 on 2025-12-11 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_paymentvoucher_employee_receiptvoucher_employee'),
        ('core', '0018_add_credit_restore_setting_and_current_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='default_cost_of_goods_account',
            field=models.ForeignKey(blank=True, help_text='حساب تكلفة المبيعات', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_cogs', to='accounting.account', verbose_name='حساب تكلفة البضاعة المباعة'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='default_inventory_account',
            field=models.ForeignKey(blank=True, help_text='الحساب الافتراضي للمخزون في فواتير المشتريات', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_inventory', to='accounting.account', verbose_name='حساب المخزون الافتراضي'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='default_purchase_account',
            field=models.ForeignKey(blank=True, help_text='الحساب الافتراضي للمشتريات (للجرد الدوري)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_purchase', to='accounting.account', verbose_name='حساب المشتريات الافتراضي'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='default_purchase_discount_account',
            field=models.ForeignKey(blank=True, help_text='حساب الخصم المكتسب على المشتريات', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_purchase_discount', to='accounting.account', verbose_name='حساب خصم المشتريات'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='default_purchase_vat_account',
            field=models.ForeignKey(blank=True, help_text='حساب ضريبة القيمة المضافة للمشتريات', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_purchase_vat', to='accounting.account', verbose_name='حساب ضريبة المشتريات'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='default_sales_account',
            field=models.ForeignKey(blank=True, help_text='الحساب الافتراضي لإيرادات المبيعات', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_sales', to='accounting.account', verbose_name='حساب المبيعات الافتراضي'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='default_sales_vat_account',
            field=models.ForeignKey(blank=True, help_text='حساب ضريبة القيمة المضافة للمبيعات', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_sales_vat', to='accounting.account', verbose_name='حساب ضريبة المبيعات'),
        ),
        migrations.AlterField(
            model_name='businesspartner',
            name='partner_type',
            field=models.CharField(choices=[('customer', 'عميل'), ('supplier', 'مورد'), ('both', 'عميل ومورد')], default='both', max_length=10, verbose_name='نوع العميل'),
        ),
    ]
