# Generated by Django 5.2.5 on 2025-09-24 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='الشركة'),
        ),
        migrations.AddField(
            model_name='account',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة'),
        ),
        migrations.AddField(
            model_name='account',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.currency', verbose_name='العملة الافتراضية'),
        ),
        migrations.AddField(
            model_name='account',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounting.account', verbose_name='الحساب الأب'),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='accounting.account', verbose_name='الحساب'),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='الشركة'),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة'),
        ),
        migrations.AddField(
            model_name='accountbalancehistory',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_history', to='accounting.account', verbose_name='الحساب'),
        ),
        migrations.AddField(
            model_name='accountbalancehistory',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تم التغيير بواسطة'),
        ),
        migrations.AddField(
            model_name='accountbalancehistory',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='الشركة'),
        ),
        migrations.AddField(
            model_name='accountbalancehistory',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة'),
        ),
        migrations.AddField(
            model_name='accountingperiod',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='الشركة'),
        ),
        migrations.AddField(
            model_name='accountingperiod',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة'),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.accountingperiod', verbose_name='الفترة المحاسبية'),
        ),
        migrations.AddField(
            model_name='account',
            name='account_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='accounting.accounttype', verbose_name='نوع الحساب'),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='الشركة'),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة'),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_cost_centers', to=settings.AUTH_USER_MODEL, verbose_name='مدير المركز'),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounting.costcenter', verbose_name='مركز التكلفة الأب'),
        ),
        migrations.AddField(
            model_name='fiscalyear',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='الشركة'),
        ),
        migrations.AddField(
            model_name='fiscalyear',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة'),
        ),
        migrations.AddField(
            model_name='accountingperiod',
            name='fiscal_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='accounting.fiscalyear', verbose_name='السنة المالية'),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='fiscal_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.fiscalyear', verbose_name='السنة المالية'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.branch', verbose_name='الفرع'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='الشركة'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='fiscal_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.fiscalyear', verbose_name='السنة المالية'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.accountingperiod', verbose_name='الفترة المحاسبية'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_journal_entries', to=settings.AUTH_USER_MODEL, verbose_name='رحل بواسطة'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='reversed_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversing_entries', to='accounting.journalentry', verbose_name='القيد العكسي'),
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.account', verbose_name='الحساب'),
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_lines', to='accounting.costcenter', verbose_name='مركز التكلفة'),
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.currency', verbose_name='العملة'),
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='journal_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.journalentry', verbose_name='القيد'),
        ),
        migrations.AddField(
            model_name='journalentrytemplate',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='الشركة'),
        ),
        migrations.AddField(
            model_name='journalentrytemplate',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.journalentrytemplate', verbose_name='القالب'),
        ),
        migrations.AddField(
            model_name='journalentrytemplateline',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.account', verbose_name='الحساب'),
        ),
        migrations.AddField(
            model_name='journalentrytemplateline',
            name='default_cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.costcenter', verbose_name='مركز التكلفة الافتراضي'),
        ),
        migrations.AddField(
            model_name='journalentrytemplateline',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_lines', to='accounting.journalentrytemplate', verbose_name='القالب'),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.branch', verbose_name='الفرع'),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='cash_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_vouchers', to='accounting.account', verbose_name='حساب الصندوق/البنك'),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='الشركة'),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة'),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.currency', verbose_name='العملة'),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='expense_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense_vouchers', to='accounting.account', verbose_name='حساب المصروف'),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='journal_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.journalentry', verbose_name='القيد المحاسبي'),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_payment_vouchers', to=settings.AUTH_USER_MODEL, verbose_name='رحل بواسطة'),
        ),
        migrations.AddField(
            model_name='receiptvoucher',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.branch', verbose_name='الفرع'),
        ),
        migrations.AddField(
            model_name='receiptvoucher',
            name='cash_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_vouchers', to='accounting.account', verbose_name='حساب الصندوق/البنك'),
        ),
        migrations.AddField(
            model_name='receiptvoucher',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='الشركة'),
        ),
        migrations.AddField(
            model_name='receiptvoucher',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة'),
        ),
        migrations.AddField(
            model_name='receiptvoucher',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.currency', verbose_name='العملة'),
        ),
        migrations.AddField(
            model_name='receiptvoucher',
            name='income_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='income_vouchers', to='accounting.account', verbose_name='حساب الإيراد'),
        ),
        migrations.AddField(
            model_name='receiptvoucher',
            name='journal_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.journalentry', verbose_name='القيد المحاسبي'),
        ),
        migrations.AddField(
            model_name='receiptvoucher',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_receipt_vouchers', to=settings.AUTH_USER_MODEL, verbose_name='رحل بواسطة'),
        ),
        migrations.AddIndex(
            model_name='accountbalancehistory',
            index=models.Index(fields=['account', '-change_date'], name='accounting__account_43c751_idx'),
        ),
        migrations.AddIndex(
            model_name='accountbalancehistory',
            index=models.Index(fields=['reference_type', 'reference_id'], name='accounting__referen_10e202_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('company', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='costcenter',
            unique_together={('company', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='fiscalyear',
            unique_together={('company', 'code')},
        ),
        migrations.AddIndex(
            model_name='accountbalance',
            index=models.Index(fields=['account', 'fiscal_year'], name='accounting__account_451e7d_idx'),
        ),
        migrations.AddIndex(
            model_name='accountbalance',
            index=models.Index(fields=['fiscal_year', 'period'], name='accounting__fiscal__a44389_idx'),
        ),
        migrations.AddIndex(
            model_name='accountbalance',
            index=models.Index(fields=['company', 'fiscal_year'], name='accounting__company_75b932_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='accountbalance',
            unique_together={('account', 'fiscal_year', 'company'), ('account', 'fiscal_year', 'period', 'company')},
        ),
        migrations.AlterUniqueTogether(
            name='journalentryline',
            unique_together={('journal_entry', 'line_number')},
        ),
        migrations.AlterUniqueTogether(
            name='journalentrytemplate',
            unique_together={('company', 'code'), ('company', 'name')},
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['entry_date', 'status'], name='accounting__entry_d_68b453_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['company', 'status'], name='accounting__company_7eceea_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['number'], name='accounting__number_879190_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='journalentry',
            unique_together={('company', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='journalentrytemplateline',
            unique_together={('template', 'line_number')},
        ),
        migrations.AlterUniqueTogether(
            name='paymentvoucher',
            unique_together={('company', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='receiptvoucher',
            unique_together={('company', 'number')},
        ),
    ]
