# Generated by Django 5.2.5 on 2025-10-06 15:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_initial'),
        ('core', '0007_pricelist_pricelistitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accountbalance',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='accountbalance',
            constraint=models.UniqueConstraint(condition=models.Q(('period__isnull', False)), fields=('account', 'fiscal_year', 'period', 'company'), name='unique_balance_with_period'),
        ),
        migrations.AddConstraint(
            model_name='accountbalance',
            constraint=models.UniqueConstraint(condition=models.Q(('period__isnull', True)), fields=('account', 'fiscal_year', 'company'), name='unique_balance_without_period'),
        ),
    ]
