# Generated by Django 5.2.5 on 2025-10-10 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_alter_accountbalance_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costcenter',
            name='cost_center_type',
            field=models.CharField(choices=[('administration', 'إدارة'), ('production', 'إنتاج'), ('sales', 'مبيعات'), ('services', 'خدمات'), ('marketing', 'تسويق'), ('maintenance', 'صيانة'), ('branch', 'فرع')], default='administration', max_length=20, verbose_name='نوع المركز'),
        ),
    ]
