# Generated by Django 5.2.5 on 2025-10-11 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_alter_costcenter_cost_center_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costcenter',
            name='cost_center_type',
            field=models.CharField(choices=[('branch', 'فرع'), ('sales', 'مبيعات'), ('services', 'خدمات'), ('administration', 'إدارة'), ('production', 'إنتاج'), ('marketing', 'تسويق'), ('maintenance', 'صيانة')], default='administration', max_length=20, verbose_name='نوع المركز'),
        ),
    ]
