# Generated by Django 5.2.5 on 2025-12-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_alter_costcenter_cost_center_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentvoucher',
            name='beneficiary_type',
            field=models.CharField(choices=[('supplier', 'مورد'), ('customer', 'عميل'), ('employee', 'موظف'), ('other', 'أخرى')], max_length=20, verbose_name='نوع المستفيد'),
        ),
        migrations.AlterField(
            model_name='receiptvoucher',
            name='payer_type',
            field=models.CharField(choices=[('customer', 'عميل'), ('supplier', 'مورد'), ('employee', 'موظف'), ('other', 'أخرى')], max_length=20, verbose_name='نوع الدافع'),
        ),
    ]
