# Generated by Django 5.2.5 on 2025-12-07 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_alter_paymentvoucher_beneficiary_type_and_more'),
        ('core', '0017_add_partner_item_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentvoucher',
            name='beneficiary_id',
        ),
        migrations.RemoveField(
            model_name='receiptvoucher',
            name='payer_id',
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='partner',
            field=models.ForeignKey(blank=True, help_text='للموردين والعملاء', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.businesspartner', verbose_name='الشريك التجاري'),
        ),
        migrations.AddField(
            model_name='receiptvoucher',
            name='partner',
            field=models.ForeignKey(blank=True, help_text='للعملاء والموردين', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.businesspartner', verbose_name='الشريك التجاري'),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='beneficiary_name',
            field=models.CharField(blank=True, help_text='للحالات الأخرى فقط', max_length=200, verbose_name='اسم المستفيد'),
        ),
        migrations.AlterField(
            model_name='receiptvoucher',
            name='received_from',
            field=models.CharField(blank=True, help_text='للحالات الأخرى فقط', max_length=200, verbose_name='مستلم من'),
        ),
    ]
