# Generated by Django 5.2.5 on 2025-12-07 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_remove_paymentvoucher_beneficiary_id_and_more'),
        ('hr', '0021_remove_jobgrade_unique_jobgrade_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentvoucher',
            name='employee',
            field=models.ForeignKey(blank=True, help_text='عند اختيار موظف', null=True, on_delete=django.db.models.deletion.PROTECT, to='hr.employee', verbose_name='الموظف'),
        ),
        migrations.AddField(
            model_name='receiptvoucher',
            name='employee',
            field=models.ForeignKey(blank=True, help_text='عند اختيار موظف', null=True, on_delete=django.db.models.deletion.PROTECT, to='hr.employee', verbose_name='الموظف'),
        ),
    ]
