# Generated by Django 5.2.5 on 2025-11-09 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_businesspartner_customer_account_and_more'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemstock',
            unique_together={('item', 'item_variant', 'warehouse', 'company')},
        ),
    ]
