# Generated by Django 5.2.5 on 2025-11-14 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_update_itemstock_unique_constraint'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockout',
            name='sales_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_outs', to='sales.salesinvoice', verbose_name='فاتورة المبيعات'),
        ),
    ]
