# Generated by Django 5.2.5 on 2025-11-21 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_week2_uom_groups'),
        ('inventory', '0003_stockout_sales_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemstock',
            name='last_purchase_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ آخر شراء'),
        ),
        migrations.AddField(
            model_name='itemstock',
            name='last_purchase_price',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='سعر الوحدة في آخر عملية شراء', max_digits=12, null=True, verbose_name='آخر سعر شراء للوحدة'),
        ),
        migrations.AddField(
            model_name='itemstock',
            name='last_purchase_total',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='إجمالي تكلفة آخر عملية شراء', max_digits=15, null=True, verbose_name='آخر سعر شراء إجمالي'),
        ),
        migrations.AddField(
            model_name='itemstock',
            name='last_supplier',
            field=models.ForeignKey(blank=True, limit_choices_to={'partner_type__in': ['supplier', 'both']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_supplied_stocks', to='core.businesspartner', verbose_name='آخر مورد'),
        ),
        migrations.AddField(
            model_name='itemstock',
            name='max_level',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='الحد الأقصى المسموح للتخزين', max_digits=12, null=True, verbose_name='الحد الأقصى للمخزون'),
        ),
        migrations.AddField(
            model_name='itemstock',
            name='min_level',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='عند الوصول لهذا الحد يتم التنبيه', max_digits=12, null=True, verbose_name='الحد الأدنى للمخزون'),
        ),
        migrations.AddField(
            model_name='itemstock',
            name='opening_balance',
            field=models.DecimalField(decimal_places=3, default=0, help_text='الرصيد عند بداية الفترة المالية', max_digits=12, verbose_name='الرصيد الافتتاحي'),
        ),
        migrations.AddField(
            model_name='itemstock',
            name='opening_value',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='قيمة الرصيد الافتتاحي'),
        ),
        migrations.AddField(
            model_name='itemstock',
            name='reorder_point',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='عند الوصول لهذه النقطة يتم طلب المزيد', max_digits=12, null=True, verbose_name='نقطة إعادة الطلب'),
        ),
        migrations.AddField(
            model_name='itemstock',
            name='storage_location',
            field=models.CharField(blank=True, help_text='الرف أو المنطقة في المستودع', max_length=100, verbose_name='موقع التخزين'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='balance_before',
            field=models.DecimalField(decimal_places=3, default=0, help_text='الرصيد قبل تطبيق هذه الحركة', max_digits=12, verbose_name='رصيد الكمية قبل الحركة'),
        ),
    ]
