# Generated by Django 5.2.5 on 2025-11-21 12:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_item_core_item_company_337b65_idx_and_more'),
        ('inventory', '0004_itemstock_last_purchase_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['movement_type', '-date'], name='inventory_s_movemen_acb4b7_idx'),
        ),
    ]
