# Generated by Django 5.2.5 on 2025-11-21 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_stockmovement_inventory_s_movemen_acb4b7_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockin',
            options={'ordering': ['-date', '-number'], 'permissions': [('can_post_stock_document', 'يمكنه ترحيل سندات المخزون')], 'verbose_name': 'سند إدخال', 'verbose_name_plural': 'سندات الإدخال'},
        ),
        migrations.AlterModelOptions(
            name='stocktransfer',
            options={'ordering': ['-date', '-number'], 'permissions': [('can_approve_transfer', 'يمكنه اعتماد التحويلات')], 'verbose_name': 'تحويل مخزني', 'verbose_name_plural': 'التحويلات المخزنية'},
        ),
    ]
