# Generated by Django 5.2.5 on 2025-11-29 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    إضافة حقل version لحماية من Race Conditions

    يضيف حقل version إلى الموديلات الحرجة:
    - ItemStock: لمنع تحديثات متزامنة للرصيد
    - StockIn: لمنع ترحيل متزامن
    - StockOut: لمنع ترحيل متزامن

    الحماية تعمل بنظام Optimistic Locking:
    1. عند القراءة، نحصل على رقم الإصدار الحالي
    2. عند التحديث، نتحقق أن رقم الإصدار لم يتغير
    3. إذا تغير (تحديث متزامن), نرفع exception
    4. إذا نجح التحديث، نزيد رقم الإصدار
    """

    dependencies = [
        ('inventory', '0007_stockreservation'),
    ]

    operations = [
        # إضافة version إلى ItemStock
        migrations.AddField(
            model_name='itemstock',
            name='version',
            field=models.IntegerField(default=0, verbose_name='رقم الإصدار'),
        ),

        # إضافة version إلى StockIn
        migrations.AddField(
            model_name='stockin',
            name='version',
            field=models.IntegerField(default=0, verbose_name='رقم الإصدار'),
        ),

        # إضافة version إلى StockOut
        migrations.AddField(
            model_name='stockout',
            name='version',
            field=models.IntegerField(default=0, verbose_name='رقم الإصدار'),
        ),
    ]
