# Generated by Django 5.2.5 on 2025-11-29 16:59

from django.db import migrations


def fix_version_defaults(apps, schema_editor):
    """Set default value for version fields in MySQL"""
    if schema_editor.connection.vendor == 'mysql':
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(
                "ALTER TABLE inventory_stockin MODIFY version INT NOT NULL DEFAULT 0"
            )
            cursor.execute(
                "ALTER TABLE inventory_stockout MODIFY version INT NOT NULL DEFAULT 0"
            )
            cursor.execute(
                "ALTER TABLE inventory_itemstock MODIFY version INT NOT NULL DEFAULT 0"
            )


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_add_version_for_optimistic_locking'),
    ]

    operations = [
        migrations.RunPython(fix_version_defaults, reverse_code=migrations.RunPython.noop),
    ]
