# Generated by Django 5.2.5 on 2025-11-29 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_partner_item_price'),
        ('inventory', '0009_fix_version_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='stockreservation',
            new_name='inventory_s_status_c656ef_idx',
            old_name='inventory_s_status_2e7d89_idx',
        ),
        migrations.RenameIndex(
            model_name='stockreservation',
            new_name='inventory_s_referen_912c56_idx',
            old_name='inventory_s_referen_d8f4a3_idx',
        ),
        migrations.RenameIndex(
            model_name='stockreservation',
            new_name='inventory_s_item_id_497eeb_idx',
            old_name='inventory_s_item_id_b5c8e2_idx',
        ),
        migrations.RemoveField(
            model_name='stockin',
            name='version',
        ),
        migrations.RemoveField(
            model_name='stockout',
            name='version',
        ),
        migrations.AddField(
            model_name='stockcount',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='تاريخ إتمام عملية الجرد', null=True, verbose_name='تاريخ الإتمام'),
        ),
        migrations.AddField(
            model_name='stockcount',
            name='processed_at',
            field=models.DateTimeField(blank=True, help_text='تاريخ معالجة الجرد وتحديث المخزون', null=True, verbose_name='تاريخ المعالجة'),
        ),
        migrations.AddField(
            model_name='stockcount',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_counts', to=settings.AUTH_USER_MODEL, verbose_name='عولج بواسطة'),
        ),
        migrations.AddField(
            model_name='stockcount',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='تاريخ بدء عملية الجرد', null=True, verbose_name='تاريخ البدء'),
        ),
        migrations.AlterField(
            model_name='itemstock',
            name='version',
            field=models.IntegerField(default=0, help_text='يستخدم لمنع التحديثات المتزامنة (Optimistic Locking)', verbose_name='رقم الإصدار'),
        ),
        migrations.AlterField(
            model_name='stockcount',
            name='status',
            field=models.CharField(choices=[('planned', 'مخطط'), ('in_progress', 'جاري'), ('completed', 'مكتمل'), ('approved', 'معتمد'), ('processed', 'معالج'), ('cancelled', 'ملغي')], default='planned', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='stockreservation',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='الشركة'),
        ),
        migrations.AlterField(
            model_name='stockreservation',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة'),
        ),
        migrations.AlterField(
            model_name='stockreservation',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.item', verbose_name='المادة'),
        ),
        migrations.AlterField(
            model_name='stockreservation',
            name='item_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.itemvariant', verbose_name='المتغير'),
        ),
        migrations.AlterField(
            model_name='stockreservation',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.warehouse', verbose_name='المستودع'),
        ),
    ]
