# Generated by Django 5.2.5 on 2025-11-14 07:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_businesspartner_customer_account_and_more'),
        ('hr', '0002_alter_employee_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.TextField(blank=True, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='basic_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الراتب الأساسي'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.currency', verbose_name='العملة'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'ذكر'), ('female', 'أنثى')], max_length=10, verbose_name='الجنس'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='job_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hr.jobtitle', verbose_name='المسمى الوظيفي'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'أعزب'), ('married', 'متزوج'), ('divorced', 'مطلق'), ('widowed', 'أرمل')], max_length=10, verbose_name='الحالة الاجتماعية'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='national_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='الرقم الوطني'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='الهاتف'),
        ),
    ]
