# Generated by Django 5.2.5 on 2025-11-26 21:31

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_partner_item_price'),
        ('hr', '0004_fix_missing_tables_and_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advance_number', models.CharField(max_length=50, unique=True, verbose_name='رقم السلفة')),
                ('advance_type', models.CharField(choices=[('salary_advance', 'سلفة راتب'), ('loan', 'قرض'), ('emergency', 'سلفة طارئة')], default='salary_advance', max_length=20, verbose_name='نوع السلفة')),
                ('request_date', models.DateField(verbose_name='تاريخ الطلب')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('reason', models.TextField(verbose_name='سبب السلفة')),
                ('installments', models.PositiveIntegerField(default=1, verbose_name='عدد الأقساط')),
                ('installment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='قيمة القسط')),
                ('start_deduction_date', models.DateField(blank=True, null=True, verbose_name='تاريخ بدء الخصم')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المبلغ المسدد')),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المبلغ المتبقي')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('approved', 'موافق عليه'), ('rejected', 'مرفوض'), ('disbursed', 'تم الصرف'), ('partially_paid', 'مسدد جزئياً'), ('fully_paid', 'مسدد بالكامل'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الموافقة')),
                ('disbursed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الصرف')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='سبب الرفض')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'سلفة',
                'verbose_name_plural': 'السلف',
                'ordering': ['-request_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdvanceInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.PositiveIntegerField(verbose_name='رقم القسط')),
                ('due_date', models.DateField(verbose_name='تاريخ الاستحقاق')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المبلغ المدفوع')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الدفع')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('deducted', 'تم الخصم'), ('paid', 'مدفوع نقداً'), ('skipped', 'تم تأجيله')], default='pending', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'قسط سلفة',
                'verbose_name_plural': 'أقساط السلف',
                'ordering': ['advance', 'installment_number'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('check_in', models.TimeField(blank=True, null=True, verbose_name='وقت الحضور')),
                ('check_out', models.TimeField(blank=True, null=True, verbose_name='وقت الانصراف')),
                ('status', models.CharField(choices=[('present', 'حاضر'), ('absent', 'غائب'), ('late', 'متأخر'), ('half_day', 'نصف يوم'), ('leave', 'إجازة'), ('holiday', 'عطلة'), ('weekend', 'عطلة نهاية الأسبوع')], default='present', max_length=20, verbose_name='الحالة')),
                ('working_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='ساعات العمل')),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='ساعات العمل الإضافي')),
                ('late_minutes', models.PositiveIntegerField(default=0, verbose_name='دقائق التأخير')),
                ('early_leave_minutes', models.PositiveIntegerField(default=0, verbose_name='دقائق المغادرة المبكرة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'سجل حضور',
                'verbose_name_plural': 'سجلات الحضور',
                'ordering': ['-date', 'employee__first_name'],
            },
        ),
        migrations.CreateModel(
            name='EarlyLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('leave_type', models.CharField(choices=[('early_leave', 'مغادرة مبكرة'), ('late_arrival', 'تأخر عن الدوام'), ('personal', 'مغادرة شخصية')], default='early_leave', max_length=20, verbose_name='نوع المغادرة')),
                ('from_time', models.TimeField(verbose_name='من الوقت')),
                ('to_time', models.TimeField(verbose_name='إلى الوقت')),
                ('minutes', models.PositiveIntegerField(default=0, verbose_name='عدد الدقائق')),
                ('reason', models.TextField(verbose_name='السبب')),
                ('is_deductible', models.BooleanField(default=False, verbose_name='يخصم من الراتب')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('approved', 'موافق عليه'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='الحالة')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الموافقة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'مغادرة',
                'verbose_name_plural': 'المغادرات',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='السنة')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='الرصيد الافتتاحي')),
                ('earned', models.DecimalField(decimal_places=2, default=0, help_text='الأيام المكتسبة خلال السنة', max_digits=5, verbose_name='المكتسب')),
                ('used', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='المستخدم')),
                ('adjustment', models.DecimalField(decimal_places=2, default=0, help_text='تعديلات يدوية على الرصيد', max_digits=5, verbose_name='التسوية')),
                ('carried_forward', models.DecimalField(decimal_places=2, default=0, help_text='الرصيد المرحل من السنة السابقة', max_digits=5, verbose_name='المرحل')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'رصيد إجازة',
                'verbose_name_plural': 'أرصدة الإجازات',
                'ordering': ['-year', 'employee__first_name'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الطلب')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('days', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='عدد الأيام')),
                ('reason', models.TextField(blank=True, verbose_name='سبب الإجازة')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('pending', 'قيد الانتظار'), ('approved', 'موافق عليه'), ('rejected', 'مرفوض'), ('cancelled', 'ملغي')], default='draft', max_length=20, verbose_name='الحالة')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الموافقة')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='سبب الرفض')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='hr/leave_attachments/', verbose_name='المرفق')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'طلب إجازة',
                'verbose_name_plural': 'طلبات الإجازات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Overtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('overtime_type', models.CharField(choices=[('regular', 'عمل إضافي عادي'), ('holiday', 'عمل في يوم عطلة'), ('weekend', 'عمل في نهاية الأسبوع')], default='regular', max_length=20, verbose_name='نوع العمل الإضافي')),
                ('start_time', models.TimeField(verbose_name='وقت البداية')),
                ('end_time', models.TimeField(verbose_name='وقت النهاية')),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='عدد الساعات')),
                ('rate', models.DecimalField(decimal_places=2, default=Decimal('1.25'), help_text='معامل الأجر الإضافي', max_digits=4, verbose_name='المعامل')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المبلغ')),
                ('reason', models.TextField(verbose_name='سبب العمل الإضافي')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('approved', 'موافق عليه'), ('rejected', 'مرفوض'), ('paid', 'مدفوع')], default='pending', max_length=20, verbose_name='الحالة')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الموافقة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'عمل إضافي',
                'verbose_name_plural': 'العمل الإضافي',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='department',
            name='unique_department_code',
        ),
        migrations.RemoveConstraint(
            model_name='employee',
            name='unique_employee_number',
        ),
        migrations.RemoveConstraint(
            model_name='employee',
            name='unique_employee_national_id',
        ),
        migrations.RemoveConstraint(
            model_name='employeecontract',
            name='unique_contract_number',
        ),
        migrations.RemoveConstraint(
            model_name='jobtitle',
            name='unique_jobtitle_code',
        ),
        migrations.RemoveConstraint(
            model_name='leavetype',
            name='unique_leavetype_code',
        ),
        migrations.RemoveConstraint(
            model_name='payrollaccountmapping',
            name='unique_payroll_mapping',
        ),
        migrations.RenameIndex(
            model_name='department',
            new_name='hr_departme_code_d27daf_idx',
            old_name='hr_departme_code_idx',
        ),
        migrations.RenameIndex(
            model_name='department',
            new_name='hr_departme_company_cb89ba_idx',
            old_name='hr_departme_company_idx',
        ),
        migrations.RenameIndex(
            model_name='employee',
            new_name='hr_employee_employe_725225_idx',
            old_name='hr_employee_empnum_idx',
        ),
        migrations.RenameIndex(
            model_name='employee',
            new_name='hr_employee_nationa_e4f2bc_idx',
            old_name='hr_employee_natid_idx',
        ),
        migrations.RenameIndex(
            model_name='employee',
            new_name='hr_employee_status_75bd6c_idx',
            old_name='hr_employee_status_idx',
        ),
        migrations.RenameIndex(
            model_name='employee',
            new_name='hr_employee_departm_fe730b_idx',
            old_name='hr_employee_dept_status_idx',
        ),
        migrations.RenameIndex(
            model_name='employee',
            new_name='hr_employee_hire_da_4d71d0_idx',
            old_name='hr_employee_hire_idx',
        ),
        migrations.RenameIndex(
            model_name='employeecontract',
            new_name='hr_employee_employe_06bab1_idx',
            old_name='hr_contract_emp_status_idx',
        ),
        migrations.RenameIndex(
            model_name='employeecontract',
            new_name='hr_employee_start_d_65707d_idx',
            old_name='hr_contract_dates_idx',
        ),
        migrations.RenameIndex(
            model_name='jobtitle',
            new_name='hr_jobtitle_departm_7495c9_idx',
            old_name='hr_jobtitle_dept_idx',
        ),
        migrations.RenameIndex(
            model_name='salaryincrement',
            new_name='hr_salaryin_employe_2b6ae8_idx',
            old_name='hr_increment_emp_status_idx',
        ),
        migrations.RenameIndex(
            model_name='salaryincrement',
            new_name='hr_salaryin_effecti_6f48ca_idx',
            old_name='hr_increment_date_idx',
        ),
        migrations.AlterUniqueTogether(
            name='leavetype',
            unique_together={('company', 'code')},
        ),
        migrations.AlterField(
            model_name='employee',
            name='job_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.jobgrade', verbose_name='الدرجة الوظيفية'),
        ),
        migrations.AlterField(
            model_name='hrsettings',
            name='default_working_days_per_month',
            field=models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='أيام العمل الشهرية الافتراضية'),
        ),
        migrations.AlterField(
            model_name='hrsettings',
            name='default_working_hours_per_day',
            field=models.DecimalField(decimal_places=2, default=8, max_digits=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)], verbose_name='ساعات العمل اليومية الافتراضية'),
        ),
        migrations.AlterField(
            model_name='hrsettings',
            name='fiscal_year_start_month',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='شهر بداية السنة المالية'),
        ),
        migrations.AlterField(
            model_name='jobgrade',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='الشركة'),
        ),
        migrations.AlterField(
            model_name='jobgrade',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة'),
        ),
        migrations.AlterField(
            model_name='jobgrade',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل'),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('company', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('company', 'employee_number'), ('company', 'national_id')},
        ),
        migrations.AlterUniqueTogether(
            name='employeecontract',
            unique_together={('company', 'contract_number')},
        ),
        migrations.AlterUniqueTogether(
            name='jobtitle',
            unique_together={('company', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='payrollaccountmapping',
            unique_together={('company', 'component')},
        ),
        migrations.AddIndex(
            model_name='jobgrade',
            index=models.Index(fields=['level'], name='hr_jobgrade_level_4d241f_idx'),
        ),
        migrations.AddField(
            model_name='advance',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_advances', to=settings.AUTH_USER_MODEL, verbose_name='وافق عليه'),
        ),
        migrations.AddField(
            model_name='advance',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advances', to='core.company', verbose_name='الشركة'),
        ),
        migrations.AddField(
            model_name='advance',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_advances', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AddField(
            model_name='advance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advances', to='hr.employee', verbose_name='الموظف'),
        ),
        migrations.AddField(
            model_name='advanceinstallment',
            name='advance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installment_records', to='hr.advance', verbose_name='السلفة'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='core.branch', verbose_name='الفرع'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='core.company', verbose_name='الشركة'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_attendances', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='hr.employee', verbose_name='الموظف'),
        ),
        migrations.AddField(
            model_name='earlyleave',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_early_leaves', to=settings.AUTH_USER_MODEL, verbose_name='وافق عليه'),
        ),
        migrations.AddField(
            model_name='earlyleave',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='early_leaves', to='core.company', verbose_name='الشركة'),
        ),
        migrations.AddField(
            model_name='earlyleave',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_early_leaves', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AddField(
            model_name='earlyleave',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='early_leaves', to='hr.employee', verbose_name='الموظف'),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='core.company', verbose_name='الشركة'),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='hr.employee', verbose_name='الموظف'),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='hr.leavetype', verbose_name='نوع الإجازة'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to=settings.AUTH_USER_MODEL, verbose_name='وافق عليه'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='core.branch', verbose_name='الفرع'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='core.company', verbose_name='الشركة'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_leave_requests', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='hr.employee', verbose_name='الموظف'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='hr.leavetype', verbose_name='نوع الإجازة'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='leave_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='hr.leaverequest', verbose_name='طلب الإجازة'),
        ),
        migrations.AddField(
            model_name='overtime',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_overtimes', to=settings.AUTH_USER_MODEL, verbose_name='وافق عليه'),
        ),
        migrations.AddField(
            model_name='overtime',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtimes', to='core.company', verbose_name='الشركة'),
        ),
        migrations.AddField(
            model_name='overtime',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_overtimes', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AddField(
            model_name='overtime',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtimes', to='hr.employee', verbose_name='الموظف'),
        ),
        migrations.RemoveField(
            model_name='leavetype',
            name='max_carry_forward',
        ),
        migrations.AlterUniqueTogether(
            name='advanceinstallment',
            unique_together={('advance', 'installment_number')},
        ),
        migrations.AlterUniqueTogether(
            name='leavebalance',
            unique_together={('employee', 'leave_type', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('employee', 'date')},
        ),
    ]
