# Generated by Django 5.2.5 on 2025-11-27 03:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_alter_costcenter_cost_center_type'),
        ('core', '0017_add_partner_item_price'),
        ('hr', '0005_advance_advanceinstallment_attendance_earlyleave_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='رقم المسير')),
                ('period_year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2020), django.core.validators.MaxValueValidator(2100)], verbose_name='السنة')),
                ('period_month', models.PositiveIntegerField(choices=[(1, 'يناير'), (2, 'فبراير'), (3, 'مارس'), (4, 'أبريل'), (5, 'مايو'), (6, 'يونيو'), (7, 'يوليو'), (8, 'أغسطس'), (9, 'سبتمبر'), (10, 'أكتوبر'), (11, 'نوفمبر'), (12, 'ديسمبر')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='الشهر')),
                ('from_date', models.DateField(verbose_name='من تاريخ')),
                ('to_date', models.DateField(verbose_name='إلى تاريخ')),
                ('total_basic', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='إجمالي الرواتب الأساسية')),
                ('total_allowances', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='إجمالي البدلات')),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='إجمالي الخصومات')),
                ('total_net', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='صافي الرواتب')),
                ('total_overtime', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='إجمالي العمل الإضافي')),
                ('total_loans', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='إجمالي أقساط السلف')),
                ('total_social_security', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='إجمالي الضمان الاجتماعي')),
                ('total_income_tax', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='إجمالي ضريبة الدخل')),
                ('employee_count', models.PositiveIntegerField(default=0, verbose_name='عدد الموظفين')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('processing', 'قيد المعالجة'), ('calculated', 'تم الحساب'), ('approved', 'معتمد'), ('paid', 'مدفوع'), ('cancelled', 'ملغي')], default='draft', max_length=20, verbose_name='الحالة')),
                ('approval_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاعتماد')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payrolls', to=settings.AUTH_USER_MODEL, verbose_name='اعتمد بواسطة')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payrolls', to='core.branch', verbose_name='الفرع')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='core.company', verbose_name='الشركة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payrolls', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payrolls', to='accounting.journalentry', verbose_name='القيد المحاسبي')),
            ],
            options={
                'verbose_name': 'مسير رواتب',
                'verbose_name_plural': 'مسيرات الرواتب',
                'ordering': ['-period_year', '-period_month'],
                'unique_together': {('company', 'period_year', 'period_month', 'branch')},
            },
        ),
        migrations.CreateModel(
            name='PayrollDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الراتب الأساسي')),
                ('working_days', models.PositiveIntegerField(default=30, verbose_name='أيام العمل المستحقة')),
                ('actual_days', models.PositiveIntegerField(default=30, verbose_name='أيام العمل الفعلية')),
                ('absent_days', models.PositiveIntegerField(default=0, verbose_name='أيام الغياب')),
                ('housing_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='بدل السكن')),
                ('transport_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='بدل النقل')),
                ('phone_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='بدل الهاتف')),
                ('food_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='بدل الطعام')),
                ('other_allowances', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='بدلات أخرى')),
                ('total_allowances', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إجمالي البدلات')),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='ساعات العمل الإضافي')),
                ('overtime_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مبلغ العمل الإضافي')),
                ('absence_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='خصم الغياب')),
                ('late_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='خصم التأخير')),
                ('loan_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='قسط السلفة')),
                ('social_security_employee', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الضمان الاجتماعي (الموظف)')),
                ('social_security_company', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الضمان الاجتماعي (الشركة)')),
                ('income_tax', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ضريبة الدخل')),
                ('other_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='خصومات أخرى')),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إجمالي الخصومات')),
                ('gross_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إجمالي الراتب')),
                ('net_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='صافي الراتب')),
                ('payment_method', models.CharField(choices=[('cash', 'نقدي'), ('bank_transfer', 'تحويل بنكي'), ('check', 'شيك')], default='bank_transfer', max_length=20, verbose_name='طريقة الدفع')),
                ('payment_reference', models.CharField(blank=True, max_length=100, verbose_name='مرجع الدفع')),
                ('is_paid', models.BooleanField(default=False, verbose_name='تم الدفع')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الدفع')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_details', to='hr.employee', verbose_name='الموظف')),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='hr.payroll', verbose_name='مسير الرواتب')),
            ],
            options={
                'verbose_name': 'تفاصيل الراتب',
                'verbose_name_plural': 'تفاصيل الرواتب',
                'ordering': ['employee__first_name'],
                'unique_together': {('payroll', 'employee')},
            },
        ),
        migrations.CreateModel(
            name='PayrollDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deduction_type', models.CharField(choices=[('absence', 'خصم غياب'), ('late', 'خصم تأخير'), ('social_security', 'ضمان اجتماعي'), ('income_tax', 'ضريبة دخل'), ('loan', 'قسط سلفة'), ('penalty', 'غرامة'), ('other', 'أخرى')], default='other', max_length=50, verbose_name='نوع الخصم')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='الوصف')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('payroll_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='hr.payrolldetail', verbose_name='تفاصيل الراتب')),
            ],
            options={
                'verbose_name': 'خصم في الراتب',
                'verbose_name_plural': 'خصومات في الرواتب',
            },
        ),
        migrations.CreateModel(
            name='PayrollAllowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowance_type', models.CharField(choices=[('housing', 'بدل سكن'), ('transport', 'بدل مواصلات'), ('phone', 'بدل هاتف'), ('food', 'بدل طعام'), ('bonus', 'مكافأة'), ('commission', 'عمولة'), ('other', 'أخرى')], default='other', max_length=50, verbose_name='نوع البدل')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='الوصف')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('payroll_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowances', to='hr.payrolldetail', verbose_name='تفاصيل الراتب')),
            ],
            options={
                'verbose_name': 'بدل في الراتب',
                'verbose_name_plural': 'بدلات في الرواتب',
            },
        ),
        migrations.CreateModel(
            name='PayrollLoanDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ')),
                ('advance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_deductions', to='hr.advance', verbose_name='السلفة')),
                ('installment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_deductions', to='hr.advanceinstallment', verbose_name='القسط')),
                ('payroll_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_deductions', to='hr.payrolldetail', verbose_name='تفاصيل الراتب')),
            ],
            options={
                'verbose_name': 'خصم سلفة في الراتب',
                'verbose_name_plural': 'خصومات السلف في الرواتب',
            },
        ),
    ]
