# Generated by Django 5.2.5 on 2025-11-27 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_partner_item_price'),
        ('hr', '0006_payroll_payrolldetail_payrolldeduction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notify_contract_expiry', models.BooleanField(default=True, verbose_name='إشعار انتهاء العقود')),
                ('contract_expiry_days', models.PositiveIntegerField(default=30, verbose_name='أيام التنبيه قبل انتهاء العقد')),
                ('notify_leave_balance', models.BooleanField(default=True, verbose_name='إشعار رصيد الإجازات')),
                ('leave_balance_threshold', models.PositiveIntegerField(default=5, verbose_name='حد رصيد الإجازات المنخفض')),
                ('notify_leave_requests', models.BooleanField(default=True, verbose_name='إشعار طلبات الإجازات')),
                ('notify_advance_dues', models.BooleanField(default=True, verbose_name='إشعار أقساط السلف')),
                ('notify_attendance', models.BooleanField(default=True, verbose_name='إشعارات الحضور')),
                ('notify_documents', models.BooleanField(default=True, verbose_name='إشعار انتهاء الوثائق')),
                ('document_expiry_days', models.PositiveIntegerField(default=30, verbose_name='أيام التنبيه قبل انتهاء الوثيقة')),
                ('email_notifications', models.BooleanField(default=False, verbose_name='إرسال بريد إلكتروني')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='الشركة')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hr_notification_settings', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'إعدادات الإشعارات',
                'verbose_name_plural': 'إعدادات الإشعارات',
                'db_table': 'hr_notification_setting',
            },
        ),
        migrations.CreateModel(
            name='HRNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notification_type', models.CharField(choices=[('contract_expiry', 'انتهاء العقد'), ('leave_balance_low', 'رصيد إجازات منخفض'), ('leave_request', 'طلب إجازة'), ('advance_due', 'قسط سلفة مستحق'), ('attendance_absent', 'غياب موظف'), ('attendance_late', 'تأخر موظف'), ('document_expiry', 'انتهاء وثيقة'), ('probation_end', 'انتهاء فترة التجربة'), ('increment_due', 'استحقاق علاوة'), ('payroll_ready', 'مسير رواتب جاهز'), ('general', 'إشعار عام')], default='general', max_length=30, verbose_name='نوع الإشعار')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('priority', models.CharField(choices=[('low', 'منخفضة'), ('medium', 'متوسطة'), ('high', 'عالية'), ('urgent', 'عاجلة')], default='medium', max_length=10, verbose_name='الأولوية')),
                ('related_object_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع الكائن المرتبط')),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='معرف الكائن المرتبط')),
                ('is_read', models.BooleanField(default=False, verbose_name='مقروءة')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ القراءة')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ انتهاء الصلاحية')),
                ('action_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='رابط الإجراء')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='الشركة')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='hr.employee', verbose_name='الموظف')),
                ('recipient', models.ForeignKey(blank=True, help_text='اتركه فارغاً للإشعارات العامة', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hr_notifications', to=settings.AUTH_USER_MODEL, verbose_name='المستلم')),
            ],
            options={
                'verbose_name': 'إشعار',
                'verbose_name_plural': 'الإشعارات',
                'db_table': 'hr_notification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='hr_notifica_recipie_e1b3a0_idx'), models.Index(fields=['notification_type'], name='hr_notifica_notific_75d8af_idx'), models.Index(fields=['company', 'created_at'], name='hr_notifica_company_529ea9_idx')],
            },
        ),
    ]
