# Generated by Django 5.2.5 on 2025-11-27 12:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_partner_item_price'),
        ('hr', '0007_notification_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Only biometric models - skip changes to existing models since DB is already correct
        migrations.CreateModel(
            name='BiometricDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الجهاز')),
                ('device_type', models.CharField(choices=[('zkteco', 'ZKTeco'), ('hikvision', 'Hikvision'), ('suprema', 'Suprema'), ('anviz', 'Anviz'), ('other', 'أخرى')], default='zkteco', max_length=20, verbose_name='نوع الجهاز')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='الرقم التسلسلي')),
                ('connection_type', models.CharField(choices=[('tcp', 'TCP/IP'), ('usb', 'USB'), ('serial', 'Serial')], default='tcp', max_length=20, verbose_name='نوع الاتصال')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('port', models.PositiveIntegerField(default=4370, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)], verbose_name='المنفذ')),
                ('device_password', models.CharField(blank=True, help_text='كلمة مرور الاتصال بالجهاز إن وجدت', max_length=50, verbose_name='كلمة مرور الجهاز')),
                ('location', models.CharField(blank=True, help_text='موقع الجهاز الفعلي', max_length=200, verbose_name='الموقع')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('inactive', 'غير نشط'), ('maintenance', 'صيانة'), ('offline', 'غير متصل')], default='active', max_length=20, verbose_name='الحالة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='آخر مزامنة')),
                ('last_connection', models.DateTimeField(blank=True, null=True, verbose_name='آخر اتصال')),
                ('auto_sync', models.BooleanField(default=True, verbose_name='مزامنة تلقائية')),
                ('sync_interval', models.PositiveIntegerField(default=15, help_text='الفترة بين كل مزامنة تلقائية', verbose_name='فترة المزامنة (دقائق)')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biometric_devices', to='core.branch', verbose_name='الفرع')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_devices', to='core.company', verbose_name='الشركة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_biometric_devices', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
            ],
            options={
                'verbose_name': 'جهاز بصمة',
                'verbose_name_plural': 'أجهزة البصمة',
                'ordering': ['name'],
                'unique_together': {('company', 'ip_address', 'port')},
            },
        ),
        migrations.CreateModel(
            name='BiometricSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('manual', 'يدوي'), ('auto', 'تلقائي'), ('scheduled', 'مجدول')], default='manual', max_length=20, verbose_name='نوع المزامنة')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('running', 'جاري التنفيذ'), ('completed', 'مكتمل'), ('failed', 'فشل'), ('partial', 'مكتمل جزئياً')], default='pending', max_length=20, verbose_name='الحالة')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت البدء')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الانتهاء')),
                ('records_fetched', models.PositiveIntegerField(default=0, verbose_name='السجلات المجلوبة')),
                ('records_processed', models.PositiveIntegerField(default=0, verbose_name='السجلات المعالجة')),
                ('records_failed', models.PositiveIntegerField(default=0, verbose_name='السجلات الفاشلة')),
                ('new_attendance_records', models.PositiveIntegerField(default=0, verbose_name='سجلات حضور جديدة')),
                ('error_message', models.TextField(blank=True, verbose_name='رسالة الخطأ')),
                ('details', models.JSONField(blank=True, null=True, verbose_name='التفاصيل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_sync_logs', to='core.company', verbose_name='الشركة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biometric_sync_logs', to=settings.AUTH_USER_MODEL, verbose_name='بواسطة')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='hr.biometricdevice', verbose_name='الجهاز')),
            ],
            options={
                'verbose_name': 'سجل مزامنة',
                'verbose_name_plural': 'سجلات المزامنة',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BiometricLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_user_id', models.CharField(max_length=50, verbose_name='رقم المستخدم في الجهاز')),
                ('punch_time', models.DateTimeField(verbose_name='وقت البصمة')),
                ('punch_type', models.CharField(choices=[('in', 'حضور'), ('out', 'انصراف'), ('break_out', 'خروج استراحة'), ('break_in', 'عودة استراحة'), ('overtime_in', 'بداية إضافي'), ('overtime_out', 'نهاية إضافي')], default='in', max_length=20, verbose_name='نوع البصمة')),
                ('verification_type', models.CharField(choices=[('fingerprint', 'بصمة'), ('face', 'وجه'), ('card', 'بطاقة'), ('password', 'كلمة مرور'), ('manual', 'يدوي')], default='fingerprint', max_length=20, verbose_name='نوع التحقق')),
                ('is_processed', models.BooleanField(default=False, verbose_name='تم المعالجة')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت المعالجة')),
                ('raw_data', models.JSONField(blank=True, null=True, verbose_name='البيانات الخام')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biometric_logs', to='hr.attendance', verbose_name='سجل الحضور')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_logs', to='core.company', verbose_name='الشركة')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='hr.biometricdevice', verbose_name='الجهاز')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biometric_logs', to='hr.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'سجل بصمة',
                'verbose_name_plural': 'سجلات البصمة',
                'ordering': ['-punch_time'],
                'unique_together': {('device', 'device_user_id', 'punch_time')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeBiometricMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_user_id', models.CharField(max_length=50, verbose_name='رقم المستخدم في الجهاز')),
                ('is_enrolled', models.BooleanField(default=False, verbose_name='مسجل في الجهاز')),
                ('enrolled_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التسجيل')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_biometric_mappings', to='core.company', verbose_name='الشركة')),
                ('device', models.ForeignKey(blank=True, help_text='اتركه فارغاً للتطبيق على جميع الأجهزة', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_mappings', to='hr.biometricdevice', verbose_name='الجهاز')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_mappings', to='hr.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'ربط بصمة موظف',
                'verbose_name_plural': 'ربط بصمات الموظفين',
                'unique_together': {('device', 'device_user_id'), ('employee', 'device')},
            },
        ),
    ]
