# Generated by Django 5.2.5 on 2025-11-27 16:08

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_partner_item_price'),
        ('hr', '0008_biometric_only'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Performance Models Only - تم إزالة التعديلات على LeaveRequest/LeaveBalance لتجنب التعارض
        migrations.CreateModel(
            name='PerformanceCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='المعيار')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='المعيار بالإنجليزية')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('criteria_type', models.CharField(choices=[('competency', 'كفاءات'), ('objective', 'أهداف'), ('behavior', 'سلوكيات'), ('skill', 'مهارات')], default='competency', max_length=20, verbose_name='نوع المعيار')),
                ('weight', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='وزن المعيار في التقييم الإجمالي', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='الوزن')),
                ('max_score', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5, verbose_name='أعلى درجة')),
                ('is_required', models.BooleanField(default=True, verbose_name='إلزامي')),
                ('applies_to_all', models.BooleanField(default=True, help_text='هل ينطبق على جميع الموظفين أم أقسام محددة', verbose_name='ينطبق على الجميع')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_criteria', to='core.company', verbose_name='الشركة')),
                ('departments', models.ManyToManyField(blank=True, help_text='الأقسام التي ينطبق عليها المعيار (إذا لم يكن للجميع)', related_name='performance_criteria', to='hr.department', verbose_name='الأقسام')),
            ],
            options={
                'verbose_name': 'معيار تقييم',
                'verbose_name_plural': 'معايير التقييم',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('achievement', 'إنجاز'), ('improvement', 'تحسين مطلوب'), ('feedback', 'ملاحظة'), ('recognition', 'تقدير'), ('warning', 'تحذير')], default='feedback', max_length=20, verbose_name='نوع الملاحظة')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('is_visible_to_employee', models.BooleanField(default=True, verbose_name='مرئي للموظف')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_notes', to='core.company', verbose_name='الشركة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_performance_notes', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_notes', to='hr.employee', verbose_name='الموظف')),
                ('noted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_given', to='hr.employee', verbose_name='بواسطة')),
            ],
            options={
                'verbose_name': 'ملاحظة أداء',
                'verbose_name_plural': 'ملاحظات الأداء',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PerformancePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الفترة')),
                ('period_type', models.CharField(choices=[('monthly', 'شهري'), ('quarterly', 'ربع سنوي'), ('semi_annual', 'نصف سنوي'), ('annual', 'سنوي')], default='annual', max_length=20, verbose_name='نوع الفترة')),
                ('year', models.PositiveIntegerField(verbose_name='السنة')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('evaluation_start', models.DateField(blank=True, help_text='تاريخ بدء إدخال التقييمات', null=True, verbose_name='بداية فترة التقييم')),
                ('evaluation_end', models.DateField(blank=True, help_text='آخر تاريخ لإدخال التقييمات', null=True, verbose_name='نهاية فترة التقييم')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('active', 'نشطة'), ('closed', 'مغلقة')], default='draft', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_periods', to='core.company', verbose_name='الشركة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_performance_periods', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
            ],
            options={
                'verbose_name': 'فترة تقييم',
                'verbose_name_plural': 'فترات التقييم',
                'ordering': ['-year', '-start_date'],
                'unique_together': {('company', 'name', 'year')},
            },
        ),
        migrations.CreateModel(
            name='PerformanceGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الهدف')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('key_results', models.TextField(blank=True, help_text='كيف سيتم قياس تحقيق الهدف', verbose_name='النتائج الرئيسية')),
                ('priority', models.CharField(choices=[('low', 'منخفضة'), ('medium', 'متوسطة'), ('high', 'عالية'), ('critical', 'حرجة')], default='medium', max_length=20, verbose_name='الأولوية')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('active', 'نشط'), ('in_progress', 'قيد التنفيذ'), ('completed', 'مكتمل'), ('cancelled', 'ملغي')], default='draft', max_length=20, verbose_name='الحالة')),
                ('weight', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='الوزن')),
                ('target_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='القيمة المستهدفة')),
                ('achieved_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='القيمة المحققة')),
                ('progress_percentage', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='نسبة الإنجاز %')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاريخ البداية')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الاستحقاق')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الإنجاز')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_goals', to='hr.employee', verbose_name='أسند بواسطة')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_goals', to='core.company', verbose_name='الشركة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_goals', to='hr.employee', verbose_name='الموظف')),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='hr.performanceperiod', verbose_name='فترة التقييم')),
            ],
            options={
                'verbose_name': 'هدف أداء',
                'verbose_name_plural': 'أهداف الأداء',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('self_evaluation', 'تقييم ذاتي'), ('manager_evaluation', 'تقييم المدير'), ('pending_approval', 'بانتظار الموافقة'), ('approved', 'معتمد'), ('rejected', 'مرفوض')], default='draft', max_length=20, verbose_name='الحالة')),
                ('self_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='التقييم الذاتي')),
                ('manager_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='تقييم المدير')),
                ('final_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='الدرجة النهائية')),
                ('grade', models.CharField(blank=True, help_text='ممتاز، جيد جداً، جيد، مقبول، ضعيف', max_length=20, verbose_name='التقدير')),
                ('self_comments', models.TextField(blank=True, verbose_name='تعليقات الموظف')),
                ('manager_comments', models.TextField(blank=True, verbose_name='تعليقات المدير')),
                ('improvement_areas', models.TextField(blank=True, verbose_name='مجالات التحسين')),
                ('strengths', models.TextField(blank=True, verbose_name='نقاط القوة')),
                ('goals_next_period', models.TextField(blank=True, verbose_name='أهداف الفترة القادمة')),
                ('self_evaluation_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التقييم الذاتي')),
                ('manager_evaluation_date', models.DateField(blank=True, null=True, verbose_name='تاريخ تقييم المدير')),
                ('approval_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الاعتماد')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_evaluations', to=settings.AUTH_USER_MODEL, verbose_name='اعتمد بواسطة')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_evaluations', to='core.company', verbose_name='الشركة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_evaluations', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_evaluations', to='hr.employee', verbose_name='الموظف')),
                ('evaluator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations_given', to='hr.employee', verbose_name='المقيّم')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='hr.performanceperiod', verbose_name='فترة التقييم')),
            ],
            options={
                'verbose_name': 'تقييم أداء',
                'verbose_name_plural': 'تقييمات الأداء',
                'ordering': ['-period__year', 'employee__first_name'],
                'unique_together': {('employee', 'period')},
            },
        ),
        migrations.CreateModel(
            name='PerformanceEvaluationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('self_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='التقييم الذاتي')),
                ('manager_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='تقييم المدير')),
                ('final_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='الدرجة النهائية')),
                ('self_comments', models.TextField(blank=True, verbose_name='تعليق الموظف')),
                ('manager_comments', models.TextField(blank=True, verbose_name='تعليق المدير')),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_details', to='hr.performancecriteria', verbose_name='المعيار')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='hr.performanceevaluation', verbose_name='التقييم')),
            ],
            options={
                'verbose_name': 'تفصيل تقييم',
                'verbose_name_plural': 'تفاصيل التقييم',
                'unique_together': {('evaluation', 'criteria')},
            },
        ),
    ]
