# Generated by Django 5.2.5 on 2025-11-29 20:05

from django.db import migrations


def fix_jobgrade_constraints(apps, schema_editor):
    """إصلاح قيود جدول JobGrade"""
    if schema_editor.connection.vendor == 'mysql':
        with schema_editor.connection.cursor() as cursor:
            # Check and drop old constraint if exists
            cursor.execute("""
                SELECT COUNT(*)
                FROM information_schema.TABLE_CONSTRAINTS
                WHERE CONSTRAINT_SCHEMA = DATABASE()
                AND TABLE_NAME = 'hr_jobgrade'
                AND CONSTRAINT_NAME = 'unique_jobgrade_code'
            """)
            if cursor.fetchone()[0] > 0:
                cursor.execute("ALTER TABLE hr_jobgrade DROP INDEX unique_jobgrade_code")

            # Check and drop old index if exists
            cursor.execute("""
                SELECT COUNT(*)
                FROM information_schema.STATISTICS
                WHERE TABLE_SCHEMA = DATABASE()
                AND TABLE_NAME = 'hr_jobgrade'
                AND INDEX_NAME = 'hr_jobgrade_level_idx'
            """)
            if cursor.fetchone()[0] > 0:
                cursor.execute("ALTER TABLE hr_jobgrade DROP INDEX hr_jobgrade_level_idx")

            # Check if the new unique constraint already exists
            cursor.execute("""
                SELECT COUNT(*)
                FROM information_schema.TABLE_CONSTRAINTS
                WHERE CONSTRAINT_SCHEMA = DATABASE()
                AND TABLE_NAME = 'hr_jobgrade'
                AND CONSTRAINT_NAME = 'hr_jobgrade_company_id_code_2b16a976_uniq'
            """)
            if cursor.fetchone()[0] == 0:
                # Only create if it doesn't exist
                cursor.execute("""
                    ALTER TABLE hr_jobgrade
                    ADD CONSTRAINT hr_jobgrade_company_id_code_2b16a976_uniq
                    UNIQUE (company_id, code)
                """)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_partner_item_price'),
        ('hr', '0011_fix_employee_nullable_fields'),
    ]

    operations = [
        migrations.RunPython(fix_jobgrade_constraints, reverse_code=migrations.RunPython.noop),
    ]
