# Generated by Django 5.2.5 on 2025-11-30 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_partner_item_price'),
        ('hr', '0014_remove_extra_earlyleave_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payroll',
            options={'ordering': ['-period_year', '-period_month'], 'verbose_name': 'كشف راتب', 'verbose_name_plural': 'كشوفات الرواتب'},
        ),
        migrations.RunSQL(
            sql="ALTER TABLE hr_jobgrade DROP INDEX IF EXISTS unique_jobgrade_code;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="ALTER TABLE hr_jobgrade DROP INDEX IF EXISTS hr_jobgrade_level_idx;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddField(
            model_name='leavetype',
            name='max_carry_forward',
            field=models.PositiveSmallIntegerField(default=0, help_text='الحد الأقصى لأيام الإجازة القابلة للترحيل', verbose_name='الحد الأقصى للترحيل'),
        ),
        migrations.AlterField(
            model_name='hrnotification',
            name='notification_type',
            field=models.CharField(choices=[('contract_expiry', 'انتهاء العقد'), ('leave_balance_low', 'رصيد إجازات منخفض'), ('leave_request', 'طلب إجازة'), ('advance_due', 'قسط سلفة مستحق'), ('attendance_absent', 'غياب موظف'), ('attendance_late', 'تأخر موظف'), ('document_expiry', 'انتهاء وثيقة'), ('probation_end', 'انتهاء فترة التجربة'), ('increment_due', 'استحقاق علاوة'), ('payroll_ready', 'كشف راتب جاهز'), ('general', 'إشعار عام')], default='general', max_length=30, verbose_name='نوع الإشعار'),
        ),
        migrations.AlterUniqueTogether(
            name='jobgrade',
            unique_together={('company', 'code')},
        ),
    ]
