# Generated by Django 5.2.5 on 2025-12-02 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0016_add_missing_payroll_fields'),
    ]

    operations = [
        # Skip these operations as the constraints don't exist in the database
        # This migration was auto-generated but the database state doesn't match
        migrations.RunSQL(
            sql="SELECT 'Skipping constraint removal - constraints do not exist' as message;",
            reverse_sql="SELECT 'No reverse operation needed' as message;"
        ),
    ]
