# Generated by Django 5.2.5 on 2025-12-07 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0020_fix_payrolldetail_columns'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='jobgrade',
            name='unique_jobgrade_code',
        ),
        migrations.RemoveIndex(
            model_name='jobgrade',
            name='hr_jobgrade_level_idx',
        ),
    ]
