# Generated by Django 5.2.5 on 2025-10-30 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_add_is_active_to_depreciation'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetlease',
            name='payment_frequency',
            field=models.CharField(choices=[('monthly', 'شهري'), ('quarterly', 'ربع سنوي'), ('semi_annual', 'نصف سنوي'), ('annual', 'سنوي')], default='monthly', help_text='تكرار دفع الأقساط', max_length=20, verbose_name='دورية الدفع'),
        ),
    ]
