# apps/assets/views/__init__.py
from .dashboard import *
from .asset_views import *
from .depreciation_views import *
from .transaction_views import *
from .maintenance_views import *
from .physical_count_views import *
from .insurance_views import *
from .lease_views import *
from .workflow_views import *
from .notification_views import *
from .report_views import *
from .api_views import *
from .accounting_config_views import *

__all__ = [
    # Dashboard
    'AssetDashboardView',
    'dashboard_stats_ajax',
    'depreciation_chart_ajax',
    'maintenance_chart_ajax',
    'asset_status_chart_ajax',

    # Asset Categories
    'AssetCategoryListView',
    'AssetCategoryCreateView',
    'AssetCategoryUpdateView',
    'AssetCategoryDeleteView',
    'AssetCategoryDetailView',
    'asset_category_datatable_ajax',
    'category_tree_ajax',
    'category_stats_ajax',
    'category_export',

    # Assets
    'AssetListView',
    'AssetCreateView',
    'AssetDetailView',
    'AssetUpdateView',
    'AssetDeleteView',
    'asset_datatable_ajax',
    'asset_autocomplete',
    'asset_stats_ajax',
    'asset_export',
    'generate_asset_number',
    'asset_barcode_pdf',
    'asset_qr_code',
    'upload_attachment',
    'delete_attachment',
    'bulk_import_assets',
    'download_import_template',
    'bulk_update_status',
    'bulk_update_location',

    # Depreciation Methods
    'DepreciationMethodListView',
    'DepreciationMethodCreateView',
    'DepreciationMethodDetailView',
    'DepreciationMethodUpdateView',
    'DepreciationMethodDeleteView',
    'depreciation_method_datatable_ajax',
    'depreciation_method_stats_ajax',
    'depreciation_method_export',

    # Asset Conditions
    'AssetConditionListView',
    'AssetConditionCreateView',
    'AssetConditionDetailView',
    'AssetConditionUpdateView',
    'AssetConditionDeleteView',
    'condition_datatable_ajax',
    'condition_stats_ajax',
    'condition_export',

    # Depreciation
    'AssetDepreciationListView',
    'AssetDepreciationDetailView',
    'AssetDepreciationUpdateView',
    'CalculateDepreciationView',
    'BulkDepreciationCalculationView',
    'bulk_depreciation_preview_ajax',
    'depreciation_datatable_ajax',
    'depreciation_schedule_ajax',
    'calculate_single_depreciation_ajax',
    'reverse_depreciation_ajax',
    'depreciation_delete_ajax',

    # Transactions
    'AssetTransactionListView',
    'AssetTransactionCreateView',
    'AssetTransactionDetailView',
    'AssetTransactionUpdateView',
    'AssetTransactionDeleteView',
    'transaction_datatable_ajax',
    'transaction_stats',
    'transaction_export',
    'PostTransactionView',
    'ApproveTransactionView',
    'CancelTransactionView',
    'SellAssetView',
    'DisposeAssetView',
    'RevalueAssetView',
    'approve_transaction_ajax',
    'cancel_transaction_ajax',
    'export_transactions_excel',

    # Transfers
    'AssetTransferListView',
    'AssetTransferCreateView',
    'AssetTransferDetailView',
    'AssetTransferUpdateView',
    'approve_transfer',
    'reject_transfer',
    'complete_transfer',
    'transfer_datatable_ajax',
    'transfer_stats_ajax',
    'transfer_export',

    # Maintenance
    'MaintenanceTypeListView',
    'MaintenanceTypeCreateView',
    'MaintenanceTypeDetailView',
    'MaintenanceTypeUpdateView',
    'MaintenanceTypeDeleteView',
    'MaintenanceScheduleListView',
    'MaintenanceScheduleCreateView',
    'MaintenanceScheduleDetailView',
    'MaintenanceScheduleUpdateView',
    'MaintenanceScheduleDeleteView',
    'schedule_datatable_ajax',
    'generate_schedule_dates',
    'AssetMaintenanceListView',
    'AssetMaintenanceCreateView',
    'AssetMaintenanceDetailView',
    'AssetMaintenanceUpdateView',
    'complete_maintenance',
    'delete_maintenance',
    'maintenance_datatable_ajax',
    'export_maintenance_list_excel',

    # Physical Count
    'PhysicalCountCycleListView',
    'PhysicalCountCycleCreateView',
    'PhysicalCountCycleDetailView',
    'PhysicalCountCycleUpdateView',
    'StartCycleView',
    'CompleteCycleView',
    'cycle_datatable_ajax',
    'PhysicalCountListView',
    'PhysicalCountCreateView',
    'PhysicalCountDetailView',
    'PhysicalCountUpdateView',
    'approve_physical_count',
    'count_datatable_ajax',
    'PhysicalCountLineUpdateView',
    'count_line_ajax',
    'barcode_scan_ajax',
    'upload_count_photo',
    'PhysicalCountAdjustmentListView',
    'PhysicalCountAdjustmentCreateView',
    'PhysicalCountAdjustmentDetailView',
    'post_adjustment',
    'adjustment_datatable_ajax',

    # Insurance
    'InsuranceCompanyListView',
    'InsuranceCompanyCreateView',
    'InsuranceCompanyDetailView',
    'InsuranceCompanyUpdateView',
    'InsuranceCompanyDeleteView',
    'AssetInsuranceListView',
    'AssetInsuranceCreateView',
    'AssetInsuranceDetailView',
    'AssetInsuranceUpdateView',
    'insurance_datatable_ajax',
    'insurance_expiring_ajax',
    'InsuranceClaimListView',
    'InsuranceClaimCreateView',
    'InsuranceClaimDetailView',
    'InsuranceClaimUpdateView',
    'approve_insurance_claim',
    'process_claim_payment',
    'claim_datatable_ajax',

    # Lease
    'AssetLeaseListView',
    'AssetLeaseCreateView',
    'AssetLeaseDetailView',
    'AssetLeaseUpdateView',
    'AssetLeaseDeleteView',
    'TerminateLeaseView',
    'RenewLeaseView',
    'ExercisePurchaseOptionView',
    'lease_datatable_ajax',
    'LeasePaymentListView',
    'LeasePaymentCreateView',
    'LeasePaymentDetailView',
    'process_lease_payment',
    'payment_datatable_ajax',
    'lease_payment_schedule_ajax',
    'bulk_process_payments',
    'export_lease_list_excel',

    # Workflow
    'ApprovalWorkflowListView',
    'ApprovalWorkflowCreateView',
    'ApprovalWorkflowDetailView',
    'ApprovalWorkflowUpdateView',
    'ApprovalWorkflowDeleteView',
    'ApprovalLevelCreateView',
    'ApprovalLevelUpdateView',
    'ApprovalLevelDeleteView',
    'ApprovalRequestListView',
    'ApprovalRequestDetailView',
    'approve_request',
    'reject_request',
    'request_datatable_ajax',
    'approval_stats_ajax',
    'request_export',
    'my_pending_approvals_ajax',

    # Notifications
    'notifications_dashboard',
    'overdue_maintenance_list',
    'upcoming_maintenance_list',
    'expiring_insurance_list',
    'overdue_lease_payments_list',
    'notification_count_ajax',
    'notification_details_ajax',

    # Reports
    'reports_dashboard',
    'asset_register_report',
    'depreciation_report',
    'maintenance_report',
    'asset_movement_report',
    'valuation_report',
    'physical_count_report',
    'export_asset_register_excel',
    'export_asset_register_pdf',
    'export_depreciation_excel',
    'export_depreciation_pdf',
    'export_maintenance_excel',
    'export_maintenance_pdf',
    'export_valuation_excel',
    'export_valuation_pdf',

    # API
    'asset_search_api',
    'asset_details_api',
    'category_assets_api',
    'asset_stats_api',
    'depreciation_schedule_api',
    'maintenance_alerts_api',
    'insurance_alerts_api',
    'barcode_scan_api',
    'asset_condition_list_api',
    'depreciation_method_list_api',
    'category_list_api',
    'validate_asset_number_api',
    'asset_qr_code_api',

    # Accounting Configuration
    'AccountingConfigListView',
    'AccountingConfigCreateView',
    'AccountingConfigDetailView',
    'AccountingConfigUpdateView',
]