# Generated by Django 5.2.5 on 2025-11-08 11:26

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_businesspartner_customer_account_and_more'),
        ('purchases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseQuotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('number', models.CharField(editable=False, max_length=50, verbose_name='رقم العرض')),
                ('date', models.DateField(verbose_name='تاريخ العرض')),
                ('valid_until', models.DateField(help_text='آخر موعد لصلاحية هذا العرض', verbose_name='صالح حتى')),
                ('supplier_quotation_number', models.CharField(blank=True, max_length=50, verbose_name='رقم عرض المورد')),
                ('payment_terms', models.TextField(blank=True, verbose_name='شروط الدفع')),
                ('delivery_terms', models.TextField(blank=True, verbose_name='شروط التسليم')),
                ('delivery_period_days', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مدة التسليم (بالأيام)')),
                ('warranty_period_months', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مدة الضمان (بالأشهر)')),
                ('subtotal', models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=15, verbose_name='المجموع الفرعي')),
                ('discount_amount', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='الخصم')),
                ('tax_amount', models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=15, verbose_name='الضريبة')),
                ('total_amount', models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=15, verbose_name='الإجمالي')),
                ('score', models.DecimalField(blank=True, decimal_places=2, help_text='التقييم من 100', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='التقييم')),
                ('evaluation_notes', models.TextField(blank=True, verbose_name='ملاحظات التقييم')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('sent', 'مرسل'), ('received', 'مستلم'), ('under_evaluation', 'تحت التقييم'), ('accepted', 'مقبول'), ('rejected', 'مرفوض'), ('awarded', 'فائز')], default='draft', max_length=20, verbose_name='الحالة')),
                ('is_awarded', models.BooleanField(default=False, verbose_name='فائز')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='سبب الرفض')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('attachment', models.FileField(blank=True, help_text='ملف PDF لعرض السعر من المورد', null=True, upload_to='quotations/%Y/%m/', verbose_name='المرفقات')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='الشركة')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.currency', verbose_name='العملة')),
                ('supplier', models.ForeignKey(limit_choices_to={'partner_type__in': ['supplier', 'both']}, on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='core.businesspartner', verbose_name='المورد')),
            ],
            options={
                'verbose_name': 'عرض سعر',
                'verbose_name_plural': 'عروض الأسعار',
                'ordering': ['-date', '-number'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseQuotationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('number', models.CharField(editable=False, max_length=50, verbose_name='رقم طلب العرض')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('subject', models.CharField(max_length=200, verbose_name='الموضوع')),
                ('description', models.TextField(blank=True, help_text='وصف تفصيلي للأصناف المطلوبة', verbose_name='الوصف')),
                ('submission_deadline', models.DateField(help_text='آخر موعد لاستلام عروض الأسعار من الموردين', verbose_name='آخر موعد لتقديم العروض')),
                ('required_delivery_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التسليم المطلوب')),
                ('payment_terms', models.TextField(blank=True, help_text='مثال: دفعة مقدمة 30%، الباقي عند التسليم', verbose_name='شروط الدفع')),
                ('delivery_terms', models.TextField(blank=True, help_text='مثال: التسليم في المستودع الرئيسي', verbose_name='شروط التسليم')),
                ('warranty_required', models.BooleanField(default=False, verbose_name='ضمان مطلوب')),
                ('warranty_period_months', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مدة الضمان (بالأشهر)')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('sent', 'مرسل للموردين'), ('receiving', 'استقبال العروض'), ('evaluating', 'تقييم العروض'), ('awarded', 'تم الترسية'), ('cancelled', 'ملغي')], default='draft', max_length=20, verbose_name='الحالة')),
                ('award_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الترسية')),
                ('award_reason', models.TextField(blank=True, help_text='لماذا تم اختيار هذا العرض', verbose_name='سبب الترسية')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('awarded_quotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_requests', to='purchases.purchasequotation', verbose_name='العرض الفائز')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='الشركة')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة')),
                ('purchase_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_requests', to='purchases.purchaserequest', verbose_name='طلب الشراء')),
            ],
            options={
                'verbose_name': 'طلب عرض أسعار',
                'verbose_name_plural': 'طلبات عروض الأسعار',
                'ordering': ['-date', '-number'],
                'unique_together': {('company', 'number')},
            },
        ),
        migrations.AddField(
            model_name='purchasequotation',
            name='quotation_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='purchases.purchasequotationrequest', verbose_name='طلب العرض'),
        ),
        migrations.CreateModel(
            name='PurchaseQuotationRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_description', models.TextField(help_text='للمواد غير الموجودة في النظام', verbose_name='وصف المادة')),
                ('specifications', models.TextField(blank=True, help_text='المواصفات الفنية التفصيلية', verbose_name='المواصفات المطلوبة')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='الكمية المطلوبة')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='الوحدة')),
                ('estimated_price', models.DecimalField(blank=True, decimal_places=3, help_text='للمرجعية فقط', max_digits=12, null=True, verbose_name='السعر التقديري')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.item', verbose_name='المادة')),
                ('quotation_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.purchasequotationrequest', verbose_name='طلب العرض')),
            ],
            options={
                'verbose_name': 'صنف طلب عرض أسعار',
                'verbose_name_plural': 'أصناف طلبات عروض الأسعار',
            },
        ),
        migrations.CreateModel(
            name='PurchaseQuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='الكمية')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='الوحدة')),
                ('unit_price', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='سعر الوحدة')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='خصم %')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='نسبة الضريبة %')),
                ('total', models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=15, verbose_name='الإجمالي')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='العلامة التجارية')),
                ('country_of_origin', models.CharField(blank=True, max_length=100, verbose_name='بلد المنشأ')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.item', verbose_name='المادة')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchases.purchasequotation', verbose_name='عرض السعر')),
                ('rfq_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotation_lines', to='purchases.purchasequotationrequestitem', verbose_name='صنف طلب العرض')),
            ],
            options={
                'verbose_name': 'سطر عرض سعر',
                'verbose_name_plural': 'سطور عروض الأسعار',
            },
        ),
        migrations.AlterUniqueTogether(
            name='purchasequotation',
            unique_together={('company', 'number')},
        ),
    ]
