# Generated by Django 5.2.5 on 2025-11-08 12:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_businesspartner_customer_account_and_more'),
        ('purchases', '0002_purchasequotation_purchasequotationrequest_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('number', models.CharField(editable=False, max_length=50, verbose_name='رقم العقد')),
                ('contract_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ العقد')),
                ('start_date', models.DateField(verbose_name='تاريخ البدء')),
                ('end_date', models.DateField(verbose_name='تاريخ الانتهاء')),
                ('contract_value', models.DecimalField(decimal_places=3, default=0, help_text='إجمالي قيمة العقد المتوقعة', max_digits=15, verbose_name='قيمة العقد')),
                ('payment_terms', models.TextField(blank=True, verbose_name='شروط الدفع')),
                ('delivery_terms', models.TextField(blank=True, verbose_name='شروط التسليم')),
                ('quality_standards', models.TextField(blank=True, help_text='المواصفات والمعايير المطلوبة', verbose_name='معايير الجودة')),
                ('penalty_terms', models.TextField(blank=True, help_text='غرامات التأخير أو عدم الالتزام', verbose_name='شروط الغرامات')),
                ('termination_terms', models.TextField(blank=True, help_text='شروط وإجراءات إنهاء العقد', verbose_name='شروط الإنهاء')),
                ('renewal_terms', models.TextField(blank=True, verbose_name='شروط التجديد')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('active', 'نشط'), ('suspended', 'معلق'), ('completed', 'مكتمل'), ('terminated', 'منهي'), ('expired', 'منتهي الصلاحية')], default='draft', max_length=20, verbose_name='الحالة')),
                ('approved', models.BooleanField(default=False, verbose_name='معتمد')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاعتماد')),
                ('total_ordered', models.DecimalField(decimal_places=3, default=0, editable=False, help_text='إجمالي قيمة أوامر الشراء المرتبطة', max_digits=15, verbose_name='إجمالي المطلوب')),
                ('total_received', models.DecimalField(decimal_places=3, default=0, editable=False, help_text='إجمالي قيمة المواد المستلمة', max_digits=15, verbose_name='إجمالي المستلم')),
                ('total_invoiced', models.DecimalField(decimal_places=3, default=0, editable=False, help_text='إجمالي قيمة الفواتير المرتبطة', max_digits=15, verbose_name='إجمالي المفوتر')),
                ('attachment', models.FileField(blank=True, help_text='نسخة ممسوحة من العقد الموقع', null=True, upload_to='contracts/', verbose_name='المرفقات')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_contracts', to=settings.AUTH_USER_MODEL, verbose_name='معتمد من')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='الشركة')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.currency', verbose_name='العملة')),
                ('supplier', models.ForeignKey(limit_choices_to={'is_supplier': True}, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_contracts', to='core.businesspartner', verbose_name='المورد')),
            ],
            options={
                'verbose_name': 'عقد شراء',
                'verbose_name_plural': 'عقود الشراء',
                'ordering': ['-contract_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseContractItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_description', models.CharField(max_length=500, verbose_name='وصف الصنف')),
                ('specifications', models.TextField(blank=True, verbose_name='المواصفات')),
                ('contracted_quantity', models.DecimalField(decimal_places=3, help_text='إجمالي الكمية خلال فترة العقد', max_digits=15, verbose_name='الكمية المتعاقد عليها')),
                ('unit_price', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='سعر الوحدة')),
                ('min_order_quantity', models.DecimalField(blank=True, decimal_places=3, help_text='أقل كمية يمكن طلبها في المرة الواحدة', max_digits=15, null=True, verbose_name='الحد الأدنى للطلب')),
                ('max_order_quantity', models.DecimalField(blank=True, decimal_places=3, help_text='أقصى كمية يمكن طلبها في المرة الواحدة', max_digits=15, null=True, verbose_name='الحد الأقصى للطلب')),
                ('ordered_quantity', models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=15, verbose_name='الكمية المطلوبة')),
                ('received_quantity', models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=15, verbose_name='الكمية المستلمة')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة الخصم')),
                ('total', models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=15, verbose_name='الإجمالي')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.purchasecontract', verbose_name='العقد')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.item', verbose_name='الصنف')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.unitofmeasure', verbose_name='الوحدة')),
            ],
            options={
                'verbose_name': 'سطر عقد',
                'verbose_name_plural': 'سطور العقود',
            },
        ),
    ]
