# Generated by Django 5.2.5 on 2025-11-09 16:36

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_businesspartner_customer_account_and_more'),
        ('inventory', '0001_initial'),
        ('purchases', '0004_alter_purchaseinvoiceitem_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchasecontract',
            options={'ordering': ['-contract_date', '-created_at'], 'permissions': [('approve_purchasecontract', 'يمكنه اعتماد عقود الشراء')], 'verbose_name': 'عقد شراء', 'verbose_name_plural': 'عقود الشراء'},
        ),
        migrations.CreateModel(
            name='GoodsReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('number', models.CharField(editable=False, max_length=50, verbose_name='رقم محضر الاستلام')),
                ('date', models.DateField(verbose_name='تاريخ الاستلام')),
                ('delivery_note_number', models.CharField(blank=True, help_text='رقم مستند التسليم الذي أرسله المورد', max_length=50, verbose_name='رقم إيصال التسليم من المورد')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التسليم الفعلي')),
                ('quality_check_status', models.CharField(choices=[('pending', 'بانتظار الفحص'), ('passed', 'مطابق'), ('partial', 'مطابق جزئياً'), ('failed', 'مرفوض')], default='pending', max_length=20, verbose_name='حالة الفحص')),
                ('quality_notes', models.TextField(blank=True, verbose_name='ملاحظات الفحص')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('confirmed', 'مؤكد'), ('invoiced', 'تم إصدار فاتورة'), ('cancelled', 'ملغي')], default='draft', max_length=20, verbose_name='الحالة')),
                ('is_posted', models.BooleanField(default=False, verbose_name='مرحل للمخزون')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.branch', verbose_name='الفرع')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='الشركة')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_receipts', to='purchases.purchaseinvoice', verbose_name='الفاتورة المرتبطة')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipts', to='purchases.purchaseorder', verbose_name='أمر الشراء')),
                ('received_by', models.ForeignKey(help_text='موظف المستودع الذي استلم البضاعة', on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipts_received', to=settings.AUTH_USER_MODEL, verbose_name='استلمها')),
                ('stock_in', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_receipts', to='inventory.stockin', verbose_name='سند الإدخال')),
                ('supplier', models.ForeignKey(limit_choices_to={'partner_type__in': ['supplier', 'both']}, on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipts', to='core.businesspartner', verbose_name='المورد')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.warehouse', verbose_name='المستودع المستلم')),
            ],
            options={
                'verbose_name': 'محضر استلام بضاعة',
                'verbose_name_plural': 'محاضر استلام البضائع',
                'ordering': ['-date', '-number'],
                'permissions': [('confirm_goods_receipt', 'يمكنه تأكيد استلام البضاعة')],
                'unique_together': {('company', 'number')},
            },
        ),
        migrations.CreateModel(
            name='GoodsReceiptLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_quantity', models.DecimalField(decimal_places=3, editable=False, help_text='من أمر الشراء', max_digits=12, verbose_name='الكمية المطلوبة')),
                ('received_quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='الكمية المستلمة')),
                ('rejected_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الكمية المرفوضة')),
                ('unit_price', models.DecimalField(decimal_places=3, editable=False, help_text='من أمر الشراء', max_digits=12, verbose_name='السعر')),
                ('batch_number', models.CharField(blank=True, max_length=50, verbose_name='رقم الدفعة')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('quality_status', models.CharField(choices=[('accepted', 'مقبول'), ('rejected', 'مرفوض'), ('partial', 'مقبول جزئياً')], default='accepted', max_length=20, verbose_name='حالة الجودة')),
                ('quality_notes', models.TextField(blank=True, verbose_name='ملاحظات الجودة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('goods_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchases.goodsreceipt', verbose_name='محضر الاستلام')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.item', verbose_name='المادة')),
                ('item_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipt_lines', to='core.itemvariant', verbose_name='المتغير')),
                ('purchase_order_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipt_lines', to='purchases.purchaseorderitem', verbose_name='سطر أمر الشراء')),
            ],
            options={
                'verbose_name': 'سطر محضر استلام',
                'verbose_name_plural': 'سطور محاضر الاستلام',
            },
        ),
    ]
