# Generated by Django 5.2.5 on 2025-11-09 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0005_alter_purchasecontract_options_goodsreceipt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='goods_receipt',
            field=models.ForeignKey(blank=True, help_text='مطابقة ثلاثية: أمر الشراء ← محضر الاستلام ← الفاتورة', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='purchases.goodsreceipt', verbose_name='محضر الاستلام'),
        ),
    ]
