# Generated by Django 5.2.5 on 2025-11-14 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_businesspartner_customer_account_and_more'),
        ('hr', '0001_initial'),
        ('purchases', '0007_add_branch_to_purchaseorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasecontract',
            name='supplier',
            field=models.ForeignKey(limit_choices_to={'partner_type__in': ['supplier', 'both']}, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_contracts', to='core.businesspartner', verbose_name='المورد'),
        ),
        # حذف الحقل القديم
        migrations.RemoveField(
            model_name='purchaserequest',
            name='department',
        ),
        # إضافة الحقل الجديد
        migrations.AddField(
            model_name='purchaserequest',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requests', to='hr.department', verbose_name='القسم'),
        ),
    ]
