# Generated by Django 5.2.5 on 2025-11-14 07:25

import django.db.models.deletion
from django.db import migrations, models


def clear_requested_by_fields(apps, schema_editor):
    """مسح حقول requested_by قبل تغيير نوعها"""
    PurchaseOrder = apps.get_model('purchases', 'PurchaseOrder')
    PurchaseRequest = apps.get_model('purchases', 'PurchaseRequest')

    # تعيين NULL للحقول (سنحتاج لإعادة تعيينها يدوياً بعد ذلك)
    PurchaseOrder.objects.all().update(requested_by=None)
    PurchaseRequest.objects.all().update(requested_by=None)


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
        ('purchases', '0008_alter_purchasecontract_supplier_and_more'),
    ]

    operations = [
        # حذف الحقول القديمة
        migrations.RemoveField(
            model_name='purchaseorder',
            name='requested_by',
        ),
        migrations.RemoveField(
            model_name='purchaserequest',
            name='requested_by',
        ),
        # إضافة الحقول الجديدة مرتبطة بـ Employee
        migrations.AddField(
            model_name='purchaseorder',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders_requested', to='hr.employee', verbose_name='طلب بواسطة', null=True, blank=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requests', to='hr.employee', verbose_name='طلب بواسطة', null=True, blank=True),
            preserve_default=False,
        ),
    ]
