# Generated by Django 5.2.5 on 2025-11-15 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_businesspartner_default_salesperson_and_more'),
        ('purchases', '0009_alter_purchaseorder_requested_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasequotationrequest',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.currency', verbose_name='العملة'),
        ),
    ]
