# Generated by Django 5.2.5 on 2025-11-17 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0010_purchasequotationrequest_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الإيصال'),
        ),
    ]
