# Generated by Django 5.2.5 on 2025-11-25 12:36

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_partner_item_price'),
        ('purchases', '0011_alter_purchaseinvoice_receipt_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoiceitem',
            name='conversion_rate',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='كم وحدة أساسية في وحدة الشراء (مثل: 1 كرتونة = 100 قطعة)', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))], verbose_name='معامل التحويل'),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceitem',
            name='purchase_quantity',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='الكمية بوحدة الشراء', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='كمية الشراء'),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceitem',
            name='purchase_unit_price',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='السعر بوحدة الشراء (مثل: 100$ للكرتونة)', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='سعر وحدة الشراء'),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceitem',
            name='purchase_uom',
            field=models.ForeignKey(blank=True, help_text='الوحدة التي يتم الشراء بها (مثل: كرتونة، صندوق)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_invoice_items_purchase_uom', to='core.unitofmeasure', verbose_name='وحدة الشراء'),
        ),
    ]
