# Generated by Django 5.2.5 on 2025-11-27 18:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_alter_costcenter_cost_center_type'),
        ('core', '0017_add_partner_item_price'),
        ('hr', '0010_remove_leavebalance_earned_and_more'),
        ('inventory', '0006_alter_stockin_options_alter_stocktransfer_options'),
        ('purchases', '0012_purchaseinvoiceitem_conversion_rate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='goodsreceipt',
            index=models.Index(fields=['company', '-date'], name='gr_company_date_idx'),
        ),
        migrations.AddIndex(
            model_name='goodsreceipt',
            index=models.Index(fields=['status', '-date'], name='gr_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='goodsreceipt',
            index=models.Index(fields=['supplier', '-date'], name='gr_supplier_date_idx'),
        ),
        migrations.AddIndex(
            model_name='goodsreceipt',
            index=models.Index(fields=['is_posted', '-date'], name='gr_posted_date_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseinvoice',
            index=models.Index(fields=['company', '-date'], name='pi_company_date_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseinvoice',
            index=models.Index(fields=['is_posted', '-date'], name='pi_posted_date_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseinvoice',
            index=models.Index(fields=['supplier', '-date'], name='pi_supplier_date_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseinvoice',
            index=models.Index(fields=['warehouse', '-date'], name='pi_warehouse_date_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseinvoice',
            index=models.Index(fields=['invoice_type', '-date'], name='pi_type_date_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['company', '-date'], name='po_company_date_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['status', '-date'], name='po_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['supplier', '-date'], name='po_supplier_date_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['is_invoiced', '-date'], name='po_invoiced_date_idx'),
        ),
    ]
