# Generated by Django 5.2.5 on 2025-11-27 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0013_goodsreceipt_gr_company_date_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_purchase_requests', to=settings.AUTH_USER_MODEL, verbose_name='معتمد من قبل'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='approved_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاعتماد'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='purchase_requests/%Y/%m/', verbose_name='مرفق'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='priority',
            field=models.CharField(choices=[('low', 'منخفضة'), ('normal', 'عادية'), ('high', 'عالية'), ('urgent', 'عاجلة')], default='normal', max_length=20, verbose_name='الأولوية'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='سبب الرفض'),
        ),
    ]
