# Generated by Django 5.2.5 on 2025-11-27 19:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0014_purchaserequest_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='discount_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='خصم (قيمة)'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='خصم %'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, help_text='المجموع بعد الخصم قبل الضريبة', max_digits=15, verbose_name='المجموع'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='tax_amount',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=12, verbose_name='قيمة الضريبة'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='tax_included',
            field=models.BooleanField(default=False, verbose_name='ضريبة مضافة شامل الضريبة'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=16, max_digits=5, verbose_name='نسبة الضريبة %'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='tax_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='نوع الضريبة'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='total',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, help_text='المجموع الكلي بعد الضريبة', max_digits=15, verbose_name='الإجمالي'),
        ),
    ]
