# Generated by Django 5.2.5 on 2025-11-28 07:28

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_partner_item_price'),
        ('hr', '0010_remove_leavebalance_earned_and_more'),
        ('purchases', '0015_add_discount_tax_fields_to_purchase_order_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='unit',
            field=models.ForeignKey(blank=True, help_text='وحدة القياس للمادة', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.unitofmeasure', verbose_name='الوحدة'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='requested_by_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_purchase_requests', to='hr.employee', verbose_name='الموظف الطالب'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoiceitem',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=16, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='نسبة الضريبة %'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='الكمية'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=16, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='نسبة الضريبة %'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requests', to=settings.AUTH_USER_MODEL, verbose_name='طلب بواسطة'),
        ),
        migrations.AlterField(
            model_name='purchaserequestitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='الكمية المطلوبة'),
        ),
    ]
