# Generated by Django 5.2.5 on 2025-11-29 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0016_add_unit_to_order_item_and_fix_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='supplier_invoice_number',
            field=models.CharField(max_length=50, verbose_name='رقم فاتورة المورد'),
        ),
    ]
