# Generated by Django 4.1.13 on 2025-08-23 06:09

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_userprofile'),
        ('accounting', '0001_initial'),
        ('base_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('partner_type', models.CharField(choices=[('customer', 'عميل'), ('supplier', 'مورد'), ('both', 'عميل ومورد')], default='customer', max_length=10, verbose_name='نوع الشريك')),
                ('code', models.CharField(max_length=50, verbose_name='الرمز')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='الاسم بالإنجليزية')),
                ('account_type', models.CharField(choices=[('cash', 'نقدي'), ('credit', 'ذمم')], default='credit', max_length=10, verbose_name='نوع الحساب')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='اسم جهة الاتصال')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='الهاتف')),
                ('mobile', models.CharField(blank=True, max_length=20, verbose_name='الموبايل')),
                ('fax', models.CharField(blank=True, max_length=20, verbose_name='الفاكس')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('website', models.URLField(blank=True, verbose_name='الموقع الإلكتروني')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='المدينة')),
                ('region', models.CharField(blank=True, max_length=50, verbose_name='المنطقة')),
                ('tax_number', models.CharField(blank=True, max_length=50, verbose_name='الرقم الضريبي')),
                ('tax_status', models.CharField(choices=[('taxable', 'خاضع'), ('exempt', 'معفى'), ('export', 'تصدير')], default='taxable', max_length=20, verbose_name='الحالة الضريبية')),
                ('commercial_register', models.CharField(blank=True, max_length=50, verbose_name='السجل التجاري')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='حد الائتمان')),
                ('credit_period', models.IntegerField(default=30, verbose_name='فترة الائتمان (أيام)')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, help_text='للعملاء فقط', max_digits=5, verbose_name='نسبة الخصم %')),
                ('customer_category', models.CharField(blank=True, choices=[('retail', 'تجزئة'), ('wholesale', 'جملة'), ('vip', 'VIP'), ('regular', 'عادي')], default='regular', max_length=20, verbose_name='تصنيف العميل')),
                ('payment_terms', models.CharField(blank=True, help_text='للموردين', max_length=100, verbose_name='شروط الدفع')),
                ('supplier_category', models.CharField(blank=True, choices=[('manufacturer', 'مصنع'), ('distributor', 'موزع'), ('importer', 'مستورد'), ('local', 'محلي')], default='local', max_length=20, verbose_name='تصنيف المورد')),
                ('rating', models.IntegerField(default=3, help_text='من 1 إلى 5 - للموردين', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='التقييم')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.branch', verbose_name='الفرع')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='الشركة')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة')),
                ('customer_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_partners', to='accounting.account', verbose_name='حساب العميل')),
                ('salesperson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_partners', to=settings.AUTH_USER_MODEL, verbose_name='مندوب المبيعات')),
                ('supplier_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_partners', to='accounting.account', verbose_name='حساب المورد')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عدّل بواسطة')),
            ],
            options={
                'verbose_name': 'شريك تجاري',
                'verbose_name_plural': 'الشركاء التجاريون',
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ItemComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='الكمية')),
                ('waste_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='نسبة الهدر %')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.branch', verbose_name='الفرع')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'مستهلك المادة',
                'verbose_name_plural': 'مستهلكات المواد',
            },
        ),
        migrations.CreateModel(
            name='ItemConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('factor', models.DecimalField(decimal_places=4, help_text='عدد وحدات "إلى" في وحدة واحدة من "من"', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='معامل التحويل')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.branch', verbose_name='الفرع')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='الشركة')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة')),
                ('from_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='from_conversions', to='base_data.unitofmeasure', verbose_name='من وحدة')),
            ],
            options={
                'verbose_name': 'معدل المادة',
                'verbose_name_plural': 'معدلات المواد',
            },
        ),
        migrations.AlterUniqueTogether(
            name='supplier',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='company',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='item',
            name='cost_of_goods_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cogs_items', to='accounting.account', verbose_name='حساب تكلفة البضاعة'),
        ),
        migrations.AddField(
            model_name='item',
            name='inventory_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='accounting.account', verbose_name='حساب المخزون'),
        ),
        migrations.AddField(
            model_name='item',
            name='is_inactive',
            field=models.BooleanField(default=False, verbose_name='غير فعالة'),
        ),
        migrations.AddField(
            model_name='item',
            name='purchase_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_items', to='accounting.account', verbose_name='حساب المشتريات'),
        ),
        migrations.AddField(
            model_name='item',
            name='sales_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_items', to='accounting.account', verbose_name='حساب المبيعات'),
        ),
        migrations.AddField(
            model_name='item',
            name='specifications',
            field=models.TextField(blank=True, verbose_name='المواصفات'),
        ),
        migrations.AddField(
            model_name='item',
            name='substitute_items',
            field=models.ManyToManyField(blank=True, to='base_data.item', verbose_name='المواد البديلة'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='warehouse_type',
            field=models.CharField(choices=[('main', 'رئيسي'), ('branch', 'فرعي'), ('transit', 'ترانزيت'), ('damaged', 'تالف')], default='branch', max_length=20, verbose_name='نوع المستودع'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
        migrations.AddField(
            model_name='itemconversion',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions', to='base_data.item', verbose_name='المادة'),
        ),
        migrations.AddField(
            model_name='itemconversion',
            name='to_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='to_conversions', to='base_data.unitofmeasure', verbose_name='إلى وحدة'),
        ),
        migrations.AddField(
            model_name='itemconversion',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عدّل بواسطة'),
        ),
        migrations.AddField(
            model_name='itemcomponent',
            name='component_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in', to='base_data.item', verbose_name='المادة المكونة'),
        ),
        migrations.AddField(
            model_name='itemcomponent',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة'),
        ),
        migrations.AddField(
            model_name='itemcomponent',
            name='parent_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='base_data.item', verbose_name='المادة الأساسية'),
        ),
        migrations.AddField(
            model_name='itemcomponent',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base_data.unitofmeasure', verbose_name='الوحدة'),
        ),
        migrations.AddField(
            model_name='itemcomponent',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عدّل بواسطة'),
        ),
        migrations.AlterUniqueTogether(
            name='itemconversion',
            unique_together={('item', 'from_unit', 'to_unit')},
        ),
        migrations.AlterUniqueTogether(
            name='itemcomponent',
            unique_together={('parent_item', 'component_item')},
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
            ],
            options={
                'verbose_name': 'عميل',
                'verbose_name_plural': 'العملاء',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('base_data.businesspartner',),
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
            ],
            options={
                'verbose_name': 'مورد',
                'verbose_name_plural': 'الموردين',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('base_data.businesspartner',),
        ),
    ]
