# Generated by Django 5.2.5 on 2025-08-26 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_data', '0002_businesspartner_itemcomponent_itemconversion_and_more'),
        ('core', '0004_user_employee_user_signature_user_theme_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='الكمية')),
                ('average_cost', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='متوسط التكلفة')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.branch', verbose_name='الفرع')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='الشركة')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_items', to='base_data.item', verbose_name='المادة')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عدّل بواسطة')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_items', to='base_data.warehouse', verbose_name='المستودع')),
            ],
            options={
                'verbose_name': 'رصيد مستودع',
                'verbose_name_plural': 'أرصدة المستودعات',
                'unique_together': {('warehouse', 'item')},
            },
        ),
    ]
